// Code generated by go-swagger; DO NOT EDIT.

package msg_vpn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// NewUpdateMsgVpnParams creates a new UpdateMsgVpnParams object
// with the default values initialized.
func NewUpdateMsgVpnParams() *UpdateMsgVpnParams {
	var ()
	return &UpdateMsgVpnParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateMsgVpnParamsWithTimeout creates a new UpdateMsgVpnParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateMsgVpnParamsWithTimeout(timeout time.Duration) *UpdateMsgVpnParams {
	var ()
	return &UpdateMsgVpnParams{

		timeout: timeout,
	}
}

// NewUpdateMsgVpnParamsWithContext creates a new UpdateMsgVpnParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateMsgVpnParamsWithContext(ctx context.Context) *UpdateMsgVpnParams {
	var ()
	return &UpdateMsgVpnParams{

		Context: ctx,
	}
}

// NewUpdateMsgVpnParamsWithHTTPClient creates a new UpdateMsgVpnParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateMsgVpnParamsWithHTTPClient(client *http.Client) *UpdateMsgVpnParams {
	var ()
	return &UpdateMsgVpnParams{
		HTTPClient: client,
	}
}

/*UpdateMsgVpnParams contains all the parameters to send to the API endpoint
for the update msg vpn operation typically these are written to a http.Request
*/
type UpdateMsgVpnParams struct {

	/*Body
	  The Message VPN object's attributes.

	*/
	Body *models.MsgVpn
	/*MsgVpnName
	  The msgVpnName of the Message VPN.

	*/
	MsgVpnName string
	/*Select
	  Include in the response only selected attributes of the object, or exclude from the response selected attributes of the object. See [Select](#select "Description of the syntax of the `select` parameter").

	*/
	Select []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update msg vpn params
func (o *UpdateMsgVpnParams) WithTimeout(timeout time.Duration) *UpdateMsgVpnParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update msg vpn params
func (o *UpdateMsgVpnParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update msg vpn params
func (o *UpdateMsgVpnParams) WithContext(ctx context.Context) *UpdateMsgVpnParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update msg vpn params
func (o *UpdateMsgVpnParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update msg vpn params
func (o *UpdateMsgVpnParams) WithHTTPClient(client *http.Client) *UpdateMsgVpnParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update msg vpn params
func (o *UpdateMsgVpnParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update msg vpn params
func (o *UpdateMsgVpnParams) WithBody(body *models.MsgVpn) *UpdateMsgVpnParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update msg vpn params
func (o *UpdateMsgVpnParams) SetBody(body *models.MsgVpn) {
	o.Body = body
}

// WithMsgVpnName adds the msgVpnName to the update msg vpn params
func (o *UpdateMsgVpnParams) WithMsgVpnName(msgVpnName string) *UpdateMsgVpnParams {
	o.SetMsgVpnName(msgVpnName)
	return o
}

// SetMsgVpnName adds the msgVpnName to the update msg vpn params
func (o *UpdateMsgVpnParams) SetMsgVpnName(msgVpnName string) {
	o.MsgVpnName = msgVpnName
}

// WithSelect adds the selectVar to the update msg vpn params
func (o *UpdateMsgVpnParams) WithSelect(selectVar []string) *UpdateMsgVpnParams {
	o.SetSelect(selectVar)
	return o
}

// SetSelect adds the select to the update msg vpn params
func (o *UpdateMsgVpnParams) SetSelect(selectVar []string) {
	o.Select = selectVar
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateMsgVpnParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param msgVpnName
	if err := r.SetPathParam("msgVpnName", o.MsgVpnName); err != nil {
		return err
	}

	valuesSelect := o.Select

	joinedSelect := swag.JoinByFormat(valuesSelect, "csv")
	// query array param select
	if err := r.SetQueryParam("select", joinedSelect...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
