// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// CreateMsgVpnDistributedCacheClusterTopicReader is a Reader for the CreateMsgVpnDistributedCacheClusterTopic structure.
type CreateMsgVpnDistributedCacheClusterTopicReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateMsgVpnDistributedCacheClusterTopicReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateMsgVpnDistributedCacheClusterTopicOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateMsgVpnDistributedCacheClusterTopicDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateMsgVpnDistributedCacheClusterTopicOK creates a CreateMsgVpnDistributedCacheClusterTopicOK with default headers values
func NewCreateMsgVpnDistributedCacheClusterTopicOK() *CreateMsgVpnDistributedCacheClusterTopicOK {
	return &CreateMsgVpnDistributedCacheClusterTopicOK{}
}

/*CreateMsgVpnDistributedCacheClusterTopicOK handles this case with default header values.

The Topic object's attributes after being created, and the request metadata.
*/
type CreateMsgVpnDistributedCacheClusterTopicOK struct {
	Payload *models.MsgVpnDistributedCacheClusterTopicResponse
}

func (o *CreateMsgVpnDistributedCacheClusterTopicOK) Error() string {
	return fmt.Sprintf("[POST /msgVpns/{msgVpnName}/distributedCaches/{cacheName}/clusters/{clusterName}/topics][%d] createMsgVpnDistributedCacheClusterTopicOK  %+v", 200, o.Payload)
}

func (o *CreateMsgVpnDistributedCacheClusterTopicOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MsgVpnDistributedCacheClusterTopicResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateMsgVpnDistributedCacheClusterTopicDefault creates a CreateMsgVpnDistributedCacheClusterTopicDefault with default headers values
func NewCreateMsgVpnDistributedCacheClusterTopicDefault(code int) *CreateMsgVpnDistributedCacheClusterTopicDefault {
	return &CreateMsgVpnDistributedCacheClusterTopicDefault{
		_statusCode: code,
	}
}

/*CreateMsgVpnDistributedCacheClusterTopicDefault handles this case with default header values.

The error response.
*/
type CreateMsgVpnDistributedCacheClusterTopicDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the create msg vpn distributed cache cluster topic default response
func (o *CreateMsgVpnDistributedCacheClusterTopicDefault) Code() int {
	return o._statusCode
}

func (o *CreateMsgVpnDistributedCacheClusterTopicDefault) Error() string {
	return fmt.Sprintf("[POST /msgVpns/{msgVpnName}/distributedCaches/{cacheName}/clusters/{clusterName}/topics][%d] createMsgVpnDistributedCacheClusterTopic default  %+v", o._statusCode, o.Payload)
}

func (o *CreateMsgVpnDistributedCacheClusterTopicDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
