// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// CreateMsgVpnJndiTopicReader is a Reader for the CreateMsgVpnJndiTopic structure.
type CreateMsgVpnJndiTopicReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateMsgVpnJndiTopicReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateMsgVpnJndiTopicOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateMsgVpnJndiTopicDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateMsgVpnJndiTopicOK creates a CreateMsgVpnJndiTopicOK with default headers values
func NewCreateMsgVpnJndiTopicOK() *CreateMsgVpnJndiTopicOK {
	return &CreateMsgVpnJndiTopicOK{}
}

/*CreateMsgVpnJndiTopicOK handles this case with default header values.

The JNDI Topic object's attributes after being created, and the request metadata.
*/
type CreateMsgVpnJndiTopicOK struct {
	Payload *models.MsgVpnJndiTopicResponse
}

func (o *CreateMsgVpnJndiTopicOK) Error() string {
	return fmt.Sprintf("[POST /msgVpns/{msgVpnName}/jndiTopics][%d] createMsgVpnJndiTopicOK  %+v", 200, o.Payload)
}

func (o *CreateMsgVpnJndiTopicOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MsgVpnJndiTopicResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateMsgVpnJndiTopicDefault creates a CreateMsgVpnJndiTopicDefault with default headers values
func NewCreateMsgVpnJndiTopicDefault(code int) *CreateMsgVpnJndiTopicDefault {
	return &CreateMsgVpnJndiTopicDefault{
		_statusCode: code,
	}
}

/*CreateMsgVpnJndiTopicDefault handles this case with default header values.

Error response
*/
type CreateMsgVpnJndiTopicDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the create msg vpn jndi topic default response
func (o *CreateMsgVpnJndiTopicDefault) Code() int {
	return o._statusCode
}

func (o *CreateMsgVpnJndiTopicDefault) Error() string {
	return fmt.Sprintf("[POST /msgVpns/{msgVpnName}/jndiTopics][%d] createMsgVpnJndiTopic default  %+v", o._statusCode, o.Payload)
}

func (o *CreateMsgVpnJndiTopicDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
