// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// DeleteMsgVpnMqttSessionSubscriptionReader is a Reader for the DeleteMsgVpnMqttSessionSubscription structure.
type DeleteMsgVpnMqttSessionSubscriptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMsgVpnMqttSessionSubscriptionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteMsgVpnMqttSessionSubscriptionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteMsgVpnMqttSessionSubscriptionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteMsgVpnMqttSessionSubscriptionOK creates a DeleteMsgVpnMqttSessionSubscriptionOK with default headers values
func NewDeleteMsgVpnMqttSessionSubscriptionOK() *DeleteMsgVpnMqttSessionSubscriptionOK {
	return &DeleteMsgVpnMqttSessionSubscriptionOK{}
}

/*DeleteMsgVpnMqttSessionSubscriptionOK handles this case with default header values.

The request metadata.
*/
type DeleteMsgVpnMqttSessionSubscriptionOK struct {
	Payload *models.SempMetaOnlyResponse
}

func (o *DeleteMsgVpnMqttSessionSubscriptionOK) Error() string {
	return fmt.Sprintf("[DELETE /msgVpns/{msgVpnName}/mqttSessions/{mqttSessionClientId},{mqttSessionVirtualRouter}/subscriptions/{subscriptionTopic}][%d] deleteMsgVpnMqttSessionSubscriptionOK  %+v", 200, o.Payload)
}

func (o *DeleteMsgVpnMqttSessionSubscriptionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteMsgVpnMqttSessionSubscriptionDefault creates a DeleteMsgVpnMqttSessionSubscriptionDefault with default headers values
func NewDeleteMsgVpnMqttSessionSubscriptionDefault(code int) *DeleteMsgVpnMqttSessionSubscriptionDefault {
	return &DeleteMsgVpnMqttSessionSubscriptionDefault{
		_statusCode: code,
	}
}

/*DeleteMsgVpnMqttSessionSubscriptionDefault handles this case with default header values.

The error response.
*/
type DeleteMsgVpnMqttSessionSubscriptionDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the delete msg vpn mqtt session subscription default response
func (o *DeleteMsgVpnMqttSessionSubscriptionDefault) Code() int {
	return o._statusCode
}

func (o *DeleteMsgVpnMqttSessionSubscriptionDefault) Error() string {
	return fmt.Sprintf("[DELETE /msgVpns/{msgVpnName}/mqttSessions/{mqttSessionClientId},{mqttSessionVirtualRouter}/subscriptions/{subscriptionTopic}][%d] deleteMsgVpnMqttSessionSubscription default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteMsgVpnMqttSessionSubscriptionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
