// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteMsgVpnReplayLogParams creates a new DeleteMsgVpnReplayLogParams object
// with the default values initialized.
func NewDeleteMsgVpnReplayLogParams() *DeleteMsgVpnReplayLogParams {
	var ()
	return &DeleteMsgVpnReplayLogParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteMsgVpnReplayLogParamsWithTimeout creates a new DeleteMsgVpnReplayLogParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteMsgVpnReplayLogParamsWithTimeout(timeout time.Duration) *DeleteMsgVpnReplayLogParams {
	var ()
	return &DeleteMsgVpnReplayLogParams{

		timeout: timeout,
	}
}

// NewDeleteMsgVpnReplayLogParamsWithContext creates a new DeleteMsgVpnReplayLogParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteMsgVpnReplayLogParamsWithContext(ctx context.Context) *DeleteMsgVpnReplayLogParams {
	var ()
	return &DeleteMsgVpnReplayLogParams{

		Context: ctx,
	}
}

// NewDeleteMsgVpnReplayLogParamsWithHTTPClient creates a new DeleteMsgVpnReplayLogParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteMsgVpnReplayLogParamsWithHTTPClient(client *http.Client) *DeleteMsgVpnReplayLogParams {
	var ()
	return &DeleteMsgVpnReplayLogParams{
		HTTPClient: client,
	}
}

/*DeleteMsgVpnReplayLogParams contains all the parameters to send to the API endpoint
for the delete msg vpn replay log operation typically these are written to a http.Request
*/
type DeleteMsgVpnReplayLogParams struct {

	/*MsgVpnName
	  The msgVpnName of the Message VPN.

	*/
	MsgVpnName string
	/*ReplayLogName
	  The replayLogName of the ReplayLog.

	*/
	ReplayLogName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete msg vpn replay log params
func (o *DeleteMsgVpnReplayLogParams) WithTimeout(timeout time.Duration) *DeleteMsgVpnReplayLogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete msg vpn replay log params
func (o *DeleteMsgVpnReplayLogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete msg vpn replay log params
func (o *DeleteMsgVpnReplayLogParams) WithContext(ctx context.Context) *DeleteMsgVpnReplayLogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete msg vpn replay log params
func (o *DeleteMsgVpnReplayLogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete msg vpn replay log params
func (o *DeleteMsgVpnReplayLogParams) WithHTTPClient(client *http.Client) *DeleteMsgVpnReplayLogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete msg vpn replay log params
func (o *DeleteMsgVpnReplayLogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMsgVpnName adds the msgVpnName to the delete msg vpn replay log params
func (o *DeleteMsgVpnReplayLogParams) WithMsgVpnName(msgVpnName string) *DeleteMsgVpnReplayLogParams {
	o.SetMsgVpnName(msgVpnName)
	return o
}

// SetMsgVpnName adds the msgVpnName to the delete msg vpn replay log params
func (o *DeleteMsgVpnReplayLogParams) SetMsgVpnName(msgVpnName string) {
	o.MsgVpnName = msgVpnName
}

// WithReplayLogName adds the replayLogName to the delete msg vpn replay log params
func (o *DeleteMsgVpnReplayLogParams) WithReplayLogName(replayLogName string) *DeleteMsgVpnReplayLogParams {
	o.SetReplayLogName(replayLogName)
	return o
}

// SetReplayLogName adds the replayLogName to the delete msg vpn replay log params
func (o *DeleteMsgVpnReplayLogParams) SetReplayLogName(replayLogName string) {
	o.ReplayLogName = replayLogName
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteMsgVpnReplayLogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param msgVpnName
	if err := r.SetPathParam("msgVpnName", o.MsgVpnName); err != nil {
		return err
	}

	// path param replayLogName
	if err := r.SetPathParam("replayLogName", o.ReplayLogName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
