// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// DeleteMsgVpnACLProfileSubscribeExceptionReader is a Reader for the DeleteMsgVpnACLProfileSubscribeException structure.
type DeleteMsgVpnACLProfileSubscribeExceptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMsgVpnACLProfileSubscribeExceptionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteMsgVpnACLProfileSubscribeExceptionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteMsgVpnACLProfileSubscribeExceptionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteMsgVpnACLProfileSubscribeExceptionOK creates a DeleteMsgVpnACLProfileSubscribeExceptionOK with default headers values
func NewDeleteMsgVpnACLProfileSubscribeExceptionOK() *DeleteMsgVpnACLProfileSubscribeExceptionOK {
	return &DeleteMsgVpnACLProfileSubscribeExceptionOK{}
}

/*DeleteMsgVpnACLProfileSubscribeExceptionOK handles this case with default header values.

The request metadata.
*/
type DeleteMsgVpnACLProfileSubscribeExceptionOK struct {
	Payload *models.SempMetaOnlyResponse
}

func (o *DeleteMsgVpnACLProfileSubscribeExceptionOK) Error() string {
	return fmt.Sprintf("[DELETE /msgVpns/{msgVpnName}/aclProfiles/{aclProfileName}/subscribeExceptions/{topicSyntax},{subscribeExceptionTopic}][%d] deleteMsgVpnAclProfileSubscribeExceptionOK  %+v", 200, o.Payload)
}

func (o *DeleteMsgVpnACLProfileSubscribeExceptionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteMsgVpnACLProfileSubscribeExceptionDefault creates a DeleteMsgVpnACLProfileSubscribeExceptionDefault with default headers values
func NewDeleteMsgVpnACLProfileSubscribeExceptionDefault(code int) *DeleteMsgVpnACLProfileSubscribeExceptionDefault {
	return &DeleteMsgVpnACLProfileSubscribeExceptionDefault{
		_statusCode: code,
	}
}

/*DeleteMsgVpnACLProfileSubscribeExceptionDefault handles this case with default header values.

Error response
*/
type DeleteMsgVpnACLProfileSubscribeExceptionDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the delete msg vpn Acl profile subscribe exception default response
func (o *DeleteMsgVpnACLProfileSubscribeExceptionDefault) Code() int {
	return o._statusCode
}

func (o *DeleteMsgVpnACLProfileSubscribeExceptionDefault) Error() string {
	return fmt.Sprintf("[DELETE /msgVpns/{msgVpnName}/aclProfiles/{aclProfileName}/subscribeExceptions/{topicSyntax},{subscribeExceptionTopic}][%d] deleteMsgVpnAclProfileSubscribeException default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteMsgVpnACLProfileSubscribeExceptionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
