// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// DeleteMsgVpnMqttSessionReader is a Reader for the DeleteMsgVpnMqttSession structure.
type DeleteMsgVpnMqttSessionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMsgVpnMqttSessionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteMsgVpnMqttSessionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteMsgVpnMqttSessionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteMsgVpnMqttSessionOK creates a DeleteMsgVpnMqttSessionOK with default headers values
func NewDeleteMsgVpnMqttSessionOK() *DeleteMsgVpnMqttSessionOK {
	return &DeleteMsgVpnMqttSessionOK{}
}

/*DeleteMsgVpnMqttSessionOK handles this case with default header values.

The request metadata.
*/
type DeleteMsgVpnMqttSessionOK struct {
	Payload *models.SempMetaOnlyResponse
}

func (o *DeleteMsgVpnMqttSessionOK) Error() string {
	return fmt.Sprintf("[DELETE /msgVpns/{msgVpnName}/mqttSessions/{mqttSessionClientId},{mqttSessionVirtualRouter}][%d] deleteMsgVpnMqttSessionOK  %+v", 200, o.Payload)
}

func (o *DeleteMsgVpnMqttSessionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteMsgVpnMqttSessionDefault creates a DeleteMsgVpnMqttSessionDefault with default headers values
func NewDeleteMsgVpnMqttSessionDefault(code int) *DeleteMsgVpnMqttSessionDefault {
	return &DeleteMsgVpnMqttSessionDefault{
		_statusCode: code,
	}
}

/*DeleteMsgVpnMqttSessionDefault handles this case with default header values.

The error response.
*/
type DeleteMsgVpnMqttSessionDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the delete msg vpn mqtt session default response
func (o *DeleteMsgVpnMqttSessionDefault) Code() int {
	return o._statusCode
}

func (o *DeleteMsgVpnMqttSessionDefault) Error() string {
	return fmt.Sprintf("[DELETE /msgVpns/{msgVpnName}/mqttSessions/{mqttSessionClientId},{mqttSessionVirtualRouter}][%d] deleteMsgVpnMqttSession default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteMsgVpnMqttSessionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
