// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteMsgVpnACLProfileClientConnectExceptionParams creates a new DeleteMsgVpnACLProfileClientConnectExceptionParams object
// with the default values initialized.
func NewDeleteMsgVpnACLProfileClientConnectExceptionParams() *DeleteMsgVpnACLProfileClientConnectExceptionParams {
	var ()
	return &DeleteMsgVpnACLProfileClientConnectExceptionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteMsgVpnACLProfileClientConnectExceptionParamsWithTimeout creates a new DeleteMsgVpnACLProfileClientConnectExceptionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteMsgVpnACLProfileClientConnectExceptionParamsWithTimeout(timeout time.Duration) *DeleteMsgVpnACLProfileClientConnectExceptionParams {
	var ()
	return &DeleteMsgVpnACLProfileClientConnectExceptionParams{

		timeout: timeout,
	}
}

// NewDeleteMsgVpnACLProfileClientConnectExceptionParamsWithContext creates a new DeleteMsgVpnACLProfileClientConnectExceptionParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteMsgVpnACLProfileClientConnectExceptionParamsWithContext(ctx context.Context) *DeleteMsgVpnACLProfileClientConnectExceptionParams {
	var ()
	return &DeleteMsgVpnACLProfileClientConnectExceptionParams{

		Context: ctx,
	}
}

// NewDeleteMsgVpnACLProfileClientConnectExceptionParamsWithHTTPClient creates a new DeleteMsgVpnACLProfileClientConnectExceptionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteMsgVpnACLProfileClientConnectExceptionParamsWithHTTPClient(client *http.Client) *DeleteMsgVpnACLProfileClientConnectExceptionParams {
	var ()
	return &DeleteMsgVpnACLProfileClientConnectExceptionParams{
		HTTPClient: client,
	}
}

/*DeleteMsgVpnACLProfileClientConnectExceptionParams contains all the parameters to send to the API endpoint
for the delete msg vpn Acl profile client connect exception operation typically these are written to a http.Request
*/
type DeleteMsgVpnACLProfileClientConnectExceptionParams struct {

	/*ACLProfileName
	  The name of the ACL Profile.

	*/
	ACLProfileName string
	/*ClientConnectExceptionAddress
	  The IP address/netmask of the client connect exception in CIDR form.

	*/
	ClientConnectExceptionAddress string
	/*MsgVpnName
	  The name of the Message VPN.

	*/
	MsgVpnName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete msg vpn Acl profile client connect exception params
func (o *DeleteMsgVpnACLProfileClientConnectExceptionParams) WithTimeout(timeout time.Duration) *DeleteMsgVpnACLProfileClientConnectExceptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete msg vpn Acl profile client connect exception params
func (o *DeleteMsgVpnACLProfileClientConnectExceptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete msg vpn Acl profile client connect exception params
func (o *DeleteMsgVpnACLProfileClientConnectExceptionParams) WithContext(ctx context.Context) *DeleteMsgVpnACLProfileClientConnectExceptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete msg vpn Acl profile client connect exception params
func (o *DeleteMsgVpnACLProfileClientConnectExceptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete msg vpn Acl profile client connect exception params
func (o *DeleteMsgVpnACLProfileClientConnectExceptionParams) WithHTTPClient(client *http.Client) *DeleteMsgVpnACLProfileClientConnectExceptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete msg vpn Acl profile client connect exception params
func (o *DeleteMsgVpnACLProfileClientConnectExceptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithACLProfileName adds the aCLProfileName to the delete msg vpn Acl profile client connect exception params
func (o *DeleteMsgVpnACLProfileClientConnectExceptionParams) WithACLProfileName(aCLProfileName string) *DeleteMsgVpnACLProfileClientConnectExceptionParams {
	o.SetACLProfileName(aCLProfileName)
	return o
}

// SetACLProfileName adds the aclProfileName to the delete msg vpn Acl profile client connect exception params
func (o *DeleteMsgVpnACLProfileClientConnectExceptionParams) SetACLProfileName(aCLProfileName string) {
	o.ACLProfileName = aCLProfileName
}

// WithClientConnectExceptionAddress adds the clientConnectExceptionAddress to the delete msg vpn Acl profile client connect exception params
func (o *DeleteMsgVpnACLProfileClientConnectExceptionParams) WithClientConnectExceptionAddress(clientConnectExceptionAddress string) *DeleteMsgVpnACLProfileClientConnectExceptionParams {
	o.SetClientConnectExceptionAddress(clientConnectExceptionAddress)
	return o
}

// SetClientConnectExceptionAddress adds the clientConnectExceptionAddress to the delete msg vpn Acl profile client connect exception params
func (o *DeleteMsgVpnACLProfileClientConnectExceptionParams) SetClientConnectExceptionAddress(clientConnectExceptionAddress string) {
	o.ClientConnectExceptionAddress = clientConnectExceptionAddress
}

// WithMsgVpnName adds the msgVpnName to the delete msg vpn Acl profile client connect exception params
func (o *DeleteMsgVpnACLProfileClientConnectExceptionParams) WithMsgVpnName(msgVpnName string) *DeleteMsgVpnACLProfileClientConnectExceptionParams {
	o.SetMsgVpnName(msgVpnName)
	return o
}

// SetMsgVpnName adds the msgVpnName to the delete msg vpn Acl profile client connect exception params
func (o *DeleteMsgVpnACLProfileClientConnectExceptionParams) SetMsgVpnName(msgVpnName string) {
	o.MsgVpnName = msgVpnName
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteMsgVpnACLProfileClientConnectExceptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param aclProfileName
	if err := r.SetPathParam("aclProfileName", o.ACLProfileName); err != nil {
		return err
	}

	// path param clientConnectExceptionAddress
	if err := r.SetPathParam("clientConnectExceptionAddress", o.ClientConnectExceptionAddress); err != nil {
		return err
	}

	// path param msgVpnName
	if err := r.SetPathParam("msgVpnName", o.MsgVpnName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
