// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// DeleteMsgVpnReplayLogReader is a Reader for the DeleteMsgVpnReplayLog structure.
type DeleteMsgVpnReplayLogReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMsgVpnReplayLogReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteMsgVpnReplayLogOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteMsgVpnReplayLogDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteMsgVpnReplayLogOK creates a DeleteMsgVpnReplayLogOK with default headers values
func NewDeleteMsgVpnReplayLogOK() *DeleteMsgVpnReplayLogOK {
	return &DeleteMsgVpnReplayLogOK{}
}

/*DeleteMsgVpnReplayLogOK handles this case with default header values.

The request metadata.
*/
type DeleteMsgVpnReplayLogOK struct {
	Payload *models.SempMetaOnlyResponse
}

func (o *DeleteMsgVpnReplayLogOK) Error() string {
	return fmt.Sprintf("[DELETE /msgVpns/{msgVpnName}/replayLogs/{replayLogName}][%d] deleteMsgVpnReplayLogOK  %+v", 200, o.Payload)
}

func (o *DeleteMsgVpnReplayLogOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteMsgVpnReplayLogDefault creates a DeleteMsgVpnReplayLogDefault with default headers values
func NewDeleteMsgVpnReplayLogDefault(code int) *DeleteMsgVpnReplayLogDefault {
	return &DeleteMsgVpnReplayLogDefault{
		_statusCode: code,
	}
}

/*DeleteMsgVpnReplayLogDefault handles this case with default header values.

The error response.
*/
type DeleteMsgVpnReplayLogDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the delete msg vpn replay log default response
func (o *DeleteMsgVpnReplayLogDefault) Code() int {
	return o._statusCode
}

func (o *DeleteMsgVpnReplayLogDefault) Error() string {
	return fmt.Sprintf("[DELETE /msgVpns/{msgVpnName}/replayLogs/{replayLogName}][%d] deleteMsgVpnReplayLog default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteMsgVpnReplayLogDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
