// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteMsgVpnACLProfileSubscribeExceptionParams creates a new DeleteMsgVpnACLProfileSubscribeExceptionParams object
// with the default values initialized.
func NewDeleteMsgVpnACLProfileSubscribeExceptionParams() *DeleteMsgVpnACLProfileSubscribeExceptionParams {
	var ()
	return &DeleteMsgVpnACLProfileSubscribeExceptionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteMsgVpnACLProfileSubscribeExceptionParamsWithTimeout creates a new DeleteMsgVpnACLProfileSubscribeExceptionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteMsgVpnACLProfileSubscribeExceptionParamsWithTimeout(timeout time.Duration) *DeleteMsgVpnACLProfileSubscribeExceptionParams {
	var ()
	return &DeleteMsgVpnACLProfileSubscribeExceptionParams{

		timeout: timeout,
	}
}

// NewDeleteMsgVpnACLProfileSubscribeExceptionParamsWithContext creates a new DeleteMsgVpnACLProfileSubscribeExceptionParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteMsgVpnACLProfileSubscribeExceptionParamsWithContext(ctx context.Context) *DeleteMsgVpnACLProfileSubscribeExceptionParams {
	var ()
	return &DeleteMsgVpnACLProfileSubscribeExceptionParams{

		Context: ctx,
	}
}

// NewDeleteMsgVpnACLProfileSubscribeExceptionParamsWithHTTPClient creates a new DeleteMsgVpnACLProfileSubscribeExceptionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteMsgVpnACLProfileSubscribeExceptionParamsWithHTTPClient(client *http.Client) *DeleteMsgVpnACLProfileSubscribeExceptionParams {
	var ()
	return &DeleteMsgVpnACLProfileSubscribeExceptionParams{
		HTTPClient: client,
	}
}

/*DeleteMsgVpnACLProfileSubscribeExceptionParams contains all the parameters to send to the API endpoint
for the delete msg vpn Acl profile subscribe exception operation typically these are written to a http.Request
*/
type DeleteMsgVpnACLProfileSubscribeExceptionParams struct {

	/*ACLProfileName
	  The name of the ACL Profile.

	*/
	ACLProfileName string
	/*MsgVpnName
	  The name of the Message VPN.

	*/
	MsgVpnName string
	/*SubscribeExceptionTopic
	  The topic for the exception to the default action taken. May include wildcard characters.

	*/
	SubscribeExceptionTopic string
	/*TopicSyntax
	  The syntax of the topic for the exception to the default action taken.

	*/
	TopicSyntax string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete msg vpn Acl profile subscribe exception params
func (o *DeleteMsgVpnACLProfileSubscribeExceptionParams) WithTimeout(timeout time.Duration) *DeleteMsgVpnACLProfileSubscribeExceptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete msg vpn Acl profile subscribe exception params
func (o *DeleteMsgVpnACLProfileSubscribeExceptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete msg vpn Acl profile subscribe exception params
func (o *DeleteMsgVpnACLProfileSubscribeExceptionParams) WithContext(ctx context.Context) *DeleteMsgVpnACLProfileSubscribeExceptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete msg vpn Acl profile subscribe exception params
func (o *DeleteMsgVpnACLProfileSubscribeExceptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete msg vpn Acl profile subscribe exception params
func (o *DeleteMsgVpnACLProfileSubscribeExceptionParams) WithHTTPClient(client *http.Client) *DeleteMsgVpnACLProfileSubscribeExceptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete msg vpn Acl profile subscribe exception params
func (o *DeleteMsgVpnACLProfileSubscribeExceptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithACLProfileName adds the aCLProfileName to the delete msg vpn Acl profile subscribe exception params
func (o *DeleteMsgVpnACLProfileSubscribeExceptionParams) WithACLProfileName(aCLProfileName string) *DeleteMsgVpnACLProfileSubscribeExceptionParams {
	o.SetACLProfileName(aCLProfileName)
	return o
}

// SetACLProfileName adds the aclProfileName to the delete msg vpn Acl profile subscribe exception params
func (o *DeleteMsgVpnACLProfileSubscribeExceptionParams) SetACLProfileName(aCLProfileName string) {
	o.ACLProfileName = aCLProfileName
}

// WithMsgVpnName adds the msgVpnName to the delete msg vpn Acl profile subscribe exception params
func (o *DeleteMsgVpnACLProfileSubscribeExceptionParams) WithMsgVpnName(msgVpnName string) *DeleteMsgVpnACLProfileSubscribeExceptionParams {
	o.SetMsgVpnName(msgVpnName)
	return o
}

// SetMsgVpnName adds the msgVpnName to the delete msg vpn Acl profile subscribe exception params
func (o *DeleteMsgVpnACLProfileSubscribeExceptionParams) SetMsgVpnName(msgVpnName string) {
	o.MsgVpnName = msgVpnName
}

// WithSubscribeExceptionTopic adds the subscribeExceptionTopic to the delete msg vpn Acl profile subscribe exception params
func (o *DeleteMsgVpnACLProfileSubscribeExceptionParams) WithSubscribeExceptionTopic(subscribeExceptionTopic string) *DeleteMsgVpnACLProfileSubscribeExceptionParams {
	o.SetSubscribeExceptionTopic(subscribeExceptionTopic)
	return o
}

// SetSubscribeExceptionTopic adds the subscribeExceptionTopic to the delete msg vpn Acl profile subscribe exception params
func (o *DeleteMsgVpnACLProfileSubscribeExceptionParams) SetSubscribeExceptionTopic(subscribeExceptionTopic string) {
	o.SubscribeExceptionTopic = subscribeExceptionTopic
}

// WithTopicSyntax adds the topicSyntax to the delete msg vpn Acl profile subscribe exception params
func (o *DeleteMsgVpnACLProfileSubscribeExceptionParams) WithTopicSyntax(topicSyntax string) *DeleteMsgVpnACLProfileSubscribeExceptionParams {
	o.SetTopicSyntax(topicSyntax)
	return o
}

// SetTopicSyntax adds the topicSyntax to the delete msg vpn Acl profile subscribe exception params
func (o *DeleteMsgVpnACLProfileSubscribeExceptionParams) SetTopicSyntax(topicSyntax string) {
	o.TopicSyntax = topicSyntax
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteMsgVpnACLProfileSubscribeExceptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param aclProfileName
	if err := r.SetPathParam("aclProfileName", o.ACLProfileName); err != nil {
		return err
	}

	// path param msgVpnName
	if err := r.SetPathParam("msgVpnName", o.MsgVpnName); err != nil {
		return err
	}

	// path param subscribeExceptionTopic
	if err := r.SetPathParam("subscribeExceptionTopic", o.SubscribeExceptionTopic); err != nil {
		return err
	}

	// path param topicSyntax
	if err := r.SetPathParam("topicSyntax", o.TopicSyntax); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
