// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// DeleteMsgVpnBridgeRemoteSubscriptionReader is a Reader for the DeleteMsgVpnBridgeRemoteSubscription structure.
type DeleteMsgVpnBridgeRemoteSubscriptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMsgVpnBridgeRemoteSubscriptionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteMsgVpnBridgeRemoteSubscriptionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteMsgVpnBridgeRemoteSubscriptionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteMsgVpnBridgeRemoteSubscriptionOK creates a DeleteMsgVpnBridgeRemoteSubscriptionOK with default headers values
func NewDeleteMsgVpnBridgeRemoteSubscriptionOK() *DeleteMsgVpnBridgeRemoteSubscriptionOK {
	return &DeleteMsgVpnBridgeRemoteSubscriptionOK{}
}

/*DeleteMsgVpnBridgeRemoteSubscriptionOK handles this case with default header values.

The request metadata.
*/
type DeleteMsgVpnBridgeRemoteSubscriptionOK struct {
	Payload *models.SempMetaOnlyResponse
}

func (o *DeleteMsgVpnBridgeRemoteSubscriptionOK) Error() string {
	return fmt.Sprintf("[DELETE /msgVpns/{msgVpnName}/bridges/{bridgeName},{bridgeVirtualRouter}/remoteSubscriptions/{remoteSubscriptionTopic}][%d] deleteMsgVpnBridgeRemoteSubscriptionOK  %+v", 200, o.Payload)
}

func (o *DeleteMsgVpnBridgeRemoteSubscriptionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteMsgVpnBridgeRemoteSubscriptionDefault creates a DeleteMsgVpnBridgeRemoteSubscriptionDefault with default headers values
func NewDeleteMsgVpnBridgeRemoteSubscriptionDefault(code int) *DeleteMsgVpnBridgeRemoteSubscriptionDefault {
	return &DeleteMsgVpnBridgeRemoteSubscriptionDefault{
		_statusCode: code,
	}
}

/*DeleteMsgVpnBridgeRemoteSubscriptionDefault handles this case with default header values.

Error response
*/
type DeleteMsgVpnBridgeRemoteSubscriptionDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the delete msg vpn bridge remote subscription default response
func (o *DeleteMsgVpnBridgeRemoteSubscriptionDefault) Code() int {
	return o._statusCode
}

func (o *DeleteMsgVpnBridgeRemoteSubscriptionDefault) Error() string {
	return fmt.Sprintf("[DELETE /msgVpns/{msgVpnName}/bridges/{bridgeName},{bridgeVirtualRouter}/remoteSubscriptions/{remoteSubscriptionTopic}][%d] deleteMsgVpnBridgeRemoteSubscription default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteMsgVpnBridgeRemoteSubscriptionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
