// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// GetMsgVpnBridgeRemoteSubscriptionsReader is a Reader for the GetMsgVpnBridgeRemoteSubscriptions structure.
type GetMsgVpnBridgeRemoteSubscriptionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMsgVpnBridgeRemoteSubscriptionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMsgVpnBridgeRemoteSubscriptionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetMsgVpnBridgeRemoteSubscriptionsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetMsgVpnBridgeRemoteSubscriptionsOK creates a GetMsgVpnBridgeRemoteSubscriptionsOK with default headers values
func NewGetMsgVpnBridgeRemoteSubscriptionsOK() *GetMsgVpnBridgeRemoteSubscriptionsOK {
	return &GetMsgVpnBridgeRemoteSubscriptionsOK{}
}

/*GetMsgVpnBridgeRemoteSubscriptionsOK handles this case with default header values.

The list of Remote Subscription objects' attributes, and the request metadata.
*/
type GetMsgVpnBridgeRemoteSubscriptionsOK struct {
	Payload *models.MsgVpnBridgeRemoteSubscriptionsResponse
}

func (o *GetMsgVpnBridgeRemoteSubscriptionsOK) Error() string {
	return fmt.Sprintf("[GET /msgVpns/{msgVpnName}/bridges/{bridgeName},{bridgeVirtualRouter}/remoteSubscriptions][%d] getMsgVpnBridgeRemoteSubscriptionsOK  %+v", 200, o.Payload)
}

func (o *GetMsgVpnBridgeRemoteSubscriptionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MsgVpnBridgeRemoteSubscriptionsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMsgVpnBridgeRemoteSubscriptionsDefault creates a GetMsgVpnBridgeRemoteSubscriptionsDefault with default headers values
func NewGetMsgVpnBridgeRemoteSubscriptionsDefault(code int) *GetMsgVpnBridgeRemoteSubscriptionsDefault {
	return &GetMsgVpnBridgeRemoteSubscriptionsDefault{
		_statusCode: code,
	}
}

/*GetMsgVpnBridgeRemoteSubscriptionsDefault handles this case with default header values.

The error response.
*/
type GetMsgVpnBridgeRemoteSubscriptionsDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the get msg vpn bridge remote subscriptions default response
func (o *GetMsgVpnBridgeRemoteSubscriptionsDefault) Code() int {
	return o._statusCode
}

func (o *GetMsgVpnBridgeRemoteSubscriptionsDefault) Error() string {
	return fmt.Sprintf("[GET /msgVpns/{msgVpnName}/bridges/{bridgeName},{bridgeVirtualRouter}/remoteSubscriptions][%d] getMsgVpnBridgeRemoteSubscriptions default  %+v", o._statusCode, o.Payload)
}

func (o *GetMsgVpnBridgeRemoteSubscriptionsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
