// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMsgVpnACLProfilePublishExceptionParams creates a new GetMsgVpnACLProfilePublishExceptionParams object
// with the default values initialized.
func NewGetMsgVpnACLProfilePublishExceptionParams() *GetMsgVpnACLProfilePublishExceptionParams {
	var ()
	return &GetMsgVpnACLProfilePublishExceptionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMsgVpnACLProfilePublishExceptionParamsWithTimeout creates a new GetMsgVpnACLProfilePublishExceptionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMsgVpnACLProfilePublishExceptionParamsWithTimeout(timeout time.Duration) *GetMsgVpnACLProfilePublishExceptionParams {
	var ()
	return &GetMsgVpnACLProfilePublishExceptionParams{

		timeout: timeout,
	}
}

// NewGetMsgVpnACLProfilePublishExceptionParamsWithContext creates a new GetMsgVpnACLProfilePublishExceptionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMsgVpnACLProfilePublishExceptionParamsWithContext(ctx context.Context) *GetMsgVpnACLProfilePublishExceptionParams {
	var ()
	return &GetMsgVpnACLProfilePublishExceptionParams{

		Context: ctx,
	}
}

// NewGetMsgVpnACLProfilePublishExceptionParamsWithHTTPClient creates a new GetMsgVpnACLProfilePublishExceptionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMsgVpnACLProfilePublishExceptionParamsWithHTTPClient(client *http.Client) *GetMsgVpnACLProfilePublishExceptionParams {
	var ()
	return &GetMsgVpnACLProfilePublishExceptionParams{
		HTTPClient: client,
	}
}

/*GetMsgVpnACLProfilePublishExceptionParams contains all the parameters to send to the API endpoint
for the get msg vpn Acl profile publish exception operation typically these are written to a http.Request
*/
type GetMsgVpnACLProfilePublishExceptionParams struct {

	/*ACLProfileName
	  The aclProfileName of the ACL Profile.

	*/
	ACLProfileName string
	/*MsgVpnName
	  The msgVpnName of the Message VPN.

	*/
	MsgVpnName string
	/*PublishExceptionTopic
	  The publishExceptionTopic of the Publish Topic Exception.

	*/
	PublishExceptionTopic string
	/*Select
	  Include in the response only selected attributes of the object, or exclude from the response selected attributes of the object. See [Select](#select "Description of the syntax of the `select` parameter").

	*/
	Select []string
	/*TopicSyntax
	  The topicSyntax of the Publish Topic Exception.

	*/
	TopicSyntax string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get msg vpn Acl profile publish exception params
func (o *GetMsgVpnACLProfilePublishExceptionParams) WithTimeout(timeout time.Duration) *GetMsgVpnACLProfilePublishExceptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get msg vpn Acl profile publish exception params
func (o *GetMsgVpnACLProfilePublishExceptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get msg vpn Acl profile publish exception params
func (o *GetMsgVpnACLProfilePublishExceptionParams) WithContext(ctx context.Context) *GetMsgVpnACLProfilePublishExceptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get msg vpn Acl profile publish exception params
func (o *GetMsgVpnACLProfilePublishExceptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get msg vpn Acl profile publish exception params
func (o *GetMsgVpnACLProfilePublishExceptionParams) WithHTTPClient(client *http.Client) *GetMsgVpnACLProfilePublishExceptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get msg vpn Acl profile publish exception params
func (o *GetMsgVpnACLProfilePublishExceptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithACLProfileName adds the aCLProfileName to the get msg vpn Acl profile publish exception params
func (o *GetMsgVpnACLProfilePublishExceptionParams) WithACLProfileName(aCLProfileName string) *GetMsgVpnACLProfilePublishExceptionParams {
	o.SetACLProfileName(aCLProfileName)
	return o
}

// SetACLProfileName adds the aclProfileName to the get msg vpn Acl profile publish exception params
func (o *GetMsgVpnACLProfilePublishExceptionParams) SetACLProfileName(aCLProfileName string) {
	o.ACLProfileName = aCLProfileName
}

// WithMsgVpnName adds the msgVpnName to the get msg vpn Acl profile publish exception params
func (o *GetMsgVpnACLProfilePublishExceptionParams) WithMsgVpnName(msgVpnName string) *GetMsgVpnACLProfilePublishExceptionParams {
	o.SetMsgVpnName(msgVpnName)
	return o
}

// SetMsgVpnName adds the msgVpnName to the get msg vpn Acl profile publish exception params
func (o *GetMsgVpnACLProfilePublishExceptionParams) SetMsgVpnName(msgVpnName string) {
	o.MsgVpnName = msgVpnName
}

// WithPublishExceptionTopic adds the publishExceptionTopic to the get msg vpn Acl profile publish exception params
func (o *GetMsgVpnACLProfilePublishExceptionParams) WithPublishExceptionTopic(publishExceptionTopic string) *GetMsgVpnACLProfilePublishExceptionParams {
	o.SetPublishExceptionTopic(publishExceptionTopic)
	return o
}

// SetPublishExceptionTopic adds the publishExceptionTopic to the get msg vpn Acl profile publish exception params
func (o *GetMsgVpnACLProfilePublishExceptionParams) SetPublishExceptionTopic(publishExceptionTopic string) {
	o.PublishExceptionTopic = publishExceptionTopic
}

// WithSelect adds the selectVar to the get msg vpn Acl profile publish exception params
func (o *GetMsgVpnACLProfilePublishExceptionParams) WithSelect(selectVar []string) *GetMsgVpnACLProfilePublishExceptionParams {
	o.SetSelect(selectVar)
	return o
}

// SetSelect adds the select to the get msg vpn Acl profile publish exception params
func (o *GetMsgVpnACLProfilePublishExceptionParams) SetSelect(selectVar []string) {
	o.Select = selectVar
}

// WithTopicSyntax adds the topicSyntax to the get msg vpn Acl profile publish exception params
func (o *GetMsgVpnACLProfilePublishExceptionParams) WithTopicSyntax(topicSyntax string) *GetMsgVpnACLProfilePublishExceptionParams {
	o.SetTopicSyntax(topicSyntax)
	return o
}

// SetTopicSyntax adds the topicSyntax to the get msg vpn Acl profile publish exception params
func (o *GetMsgVpnACLProfilePublishExceptionParams) SetTopicSyntax(topicSyntax string) {
	o.TopicSyntax = topicSyntax
}

// WriteToRequest writes these params to a swagger request
func (o *GetMsgVpnACLProfilePublishExceptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param aclProfileName
	if err := r.SetPathParam("aclProfileName", o.ACLProfileName); err != nil {
		return err
	}

	// path param msgVpnName
	if err := r.SetPathParam("msgVpnName", o.MsgVpnName); err != nil {
		return err
	}

	// path param publishExceptionTopic
	if err := r.SetPathParam("publishExceptionTopic", o.PublishExceptionTopic); err != nil {
		return err
	}

	valuesSelect := o.Select

	joinedSelect := swag.JoinByFormat(valuesSelect, "csv")
	// query array param select
	if err := r.SetQueryParam("select", joinedSelect...); err != nil {
		return err
	}

	// path param topicSyntax
	if err := r.SetPathParam("topicSyntax", o.TopicSyntax); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
