// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// GetMsgVpnTopicEndpointReader is a Reader for the GetMsgVpnTopicEndpoint structure.
type GetMsgVpnTopicEndpointReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMsgVpnTopicEndpointReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMsgVpnTopicEndpointOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetMsgVpnTopicEndpointDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetMsgVpnTopicEndpointOK creates a GetMsgVpnTopicEndpointOK with default headers values
func NewGetMsgVpnTopicEndpointOK() *GetMsgVpnTopicEndpointOK {
	return &GetMsgVpnTopicEndpointOK{}
}

/*GetMsgVpnTopicEndpointOK handles this case with default header values.

The Topic Endpoint object's attributes, and the request metadata.
*/
type GetMsgVpnTopicEndpointOK struct {
	Payload *models.MsgVpnTopicEndpointResponse
}

func (o *GetMsgVpnTopicEndpointOK) Error() string {
	return fmt.Sprintf("[GET /msgVpns/{msgVpnName}/topicEndpoints/{topicEndpointName}][%d] getMsgVpnTopicEndpointOK  %+v", 200, o.Payload)
}

func (o *GetMsgVpnTopicEndpointOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MsgVpnTopicEndpointResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMsgVpnTopicEndpointDefault creates a GetMsgVpnTopicEndpointDefault with default headers values
func NewGetMsgVpnTopicEndpointDefault(code int) *GetMsgVpnTopicEndpointDefault {
	return &GetMsgVpnTopicEndpointDefault{
		_statusCode: code,
	}
}

/*GetMsgVpnTopicEndpointDefault handles this case with default header values.

Error response
*/
type GetMsgVpnTopicEndpointDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the get msg vpn topic endpoint default response
func (o *GetMsgVpnTopicEndpointDefault) Code() int {
	return o._statusCode
}

func (o *GetMsgVpnTopicEndpointDefault) Error() string {
	return fmt.Sprintf("[GET /msgVpns/{msgVpnName}/topicEndpoints/{topicEndpointName}][%d] getMsgVpnTopicEndpoint default  %+v", o._statusCode, o.Payload)
}

func (o *GetMsgVpnTopicEndpointDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
