// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// GetMsgVpnDistributedCachesReader is a Reader for the GetMsgVpnDistributedCaches structure.
type GetMsgVpnDistributedCachesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMsgVpnDistributedCachesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMsgVpnDistributedCachesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetMsgVpnDistributedCachesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetMsgVpnDistributedCachesOK creates a GetMsgVpnDistributedCachesOK with default headers values
func NewGetMsgVpnDistributedCachesOK() *GetMsgVpnDistributedCachesOK {
	return &GetMsgVpnDistributedCachesOK{}
}

/*GetMsgVpnDistributedCachesOK handles this case with default header values.

The list of Distributed Cache objects' attributes, and the request metadata.
*/
type GetMsgVpnDistributedCachesOK struct {
	Payload *models.MsgVpnDistributedCachesResponse
}

func (o *GetMsgVpnDistributedCachesOK) Error() string {
	return fmt.Sprintf("[GET /msgVpns/{msgVpnName}/distributedCaches][%d] getMsgVpnDistributedCachesOK  %+v", 200, o.Payload)
}

func (o *GetMsgVpnDistributedCachesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MsgVpnDistributedCachesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMsgVpnDistributedCachesDefault creates a GetMsgVpnDistributedCachesDefault with default headers values
func NewGetMsgVpnDistributedCachesDefault(code int) *GetMsgVpnDistributedCachesDefault {
	return &GetMsgVpnDistributedCachesDefault{
		_statusCode: code,
	}
}

/*GetMsgVpnDistributedCachesDefault handles this case with default header values.

The error response.
*/
type GetMsgVpnDistributedCachesDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the get msg vpn distributed caches default response
func (o *GetMsgVpnDistributedCachesDefault) Code() int {
	return o._statusCode
}

func (o *GetMsgVpnDistributedCachesDefault) Error() string {
	return fmt.Sprintf("[GET /msgVpns/{msgVpnName}/distributedCaches][%d] getMsgVpnDistributedCaches default  %+v", o._statusCode, o.Payload)
}

func (o *GetMsgVpnDistributedCachesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
