// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// GetMsgVpnMqttSessionsReader is a Reader for the GetMsgVpnMqttSessions structure.
type GetMsgVpnMqttSessionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMsgVpnMqttSessionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMsgVpnMqttSessionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetMsgVpnMqttSessionsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetMsgVpnMqttSessionsOK creates a GetMsgVpnMqttSessionsOK with default headers values
func NewGetMsgVpnMqttSessionsOK() *GetMsgVpnMqttSessionsOK {
	return &GetMsgVpnMqttSessionsOK{}
}

/*GetMsgVpnMqttSessionsOK handles this case with default header values.

The list of MQTT Session objects' attributes, and the request metadata.
*/
type GetMsgVpnMqttSessionsOK struct {
	Payload *models.MsgVpnMqttSessionsResponse
}

func (o *GetMsgVpnMqttSessionsOK) Error() string {
	return fmt.Sprintf("[GET /msgVpns/{msgVpnName}/mqttSessions][%d] getMsgVpnMqttSessionsOK  %+v", 200, o.Payload)
}

func (o *GetMsgVpnMqttSessionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MsgVpnMqttSessionsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMsgVpnMqttSessionsDefault creates a GetMsgVpnMqttSessionsDefault with default headers values
func NewGetMsgVpnMqttSessionsDefault(code int) *GetMsgVpnMqttSessionsDefault {
	return &GetMsgVpnMqttSessionsDefault{
		_statusCode: code,
	}
}

/*GetMsgVpnMqttSessionsDefault handles this case with default header values.

Error response
*/
type GetMsgVpnMqttSessionsDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the get msg vpn mqtt sessions default response
func (o *GetMsgVpnMqttSessionsDefault) Code() int {
	return o._statusCode
}

func (o *GetMsgVpnMqttSessionsDefault) Error() string {
	return fmt.Sprintf("[GET /msgVpns/{msgVpnName}/mqttSessions][%d] getMsgVpnMqttSessions default  %+v", o._statusCode, o.Payload)
}

func (o *GetMsgVpnMqttSessionsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
