// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMsgVpnReplicatedTopicParams creates a new GetMsgVpnReplicatedTopicParams object
// with the default values initialized.
func NewGetMsgVpnReplicatedTopicParams() *GetMsgVpnReplicatedTopicParams {
	var ()
	return &GetMsgVpnReplicatedTopicParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMsgVpnReplicatedTopicParamsWithTimeout creates a new GetMsgVpnReplicatedTopicParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMsgVpnReplicatedTopicParamsWithTimeout(timeout time.Duration) *GetMsgVpnReplicatedTopicParams {
	var ()
	return &GetMsgVpnReplicatedTopicParams{

		timeout: timeout,
	}
}

// NewGetMsgVpnReplicatedTopicParamsWithContext creates a new GetMsgVpnReplicatedTopicParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMsgVpnReplicatedTopicParamsWithContext(ctx context.Context) *GetMsgVpnReplicatedTopicParams {
	var ()
	return &GetMsgVpnReplicatedTopicParams{

		Context: ctx,
	}
}

// NewGetMsgVpnReplicatedTopicParamsWithHTTPClient creates a new GetMsgVpnReplicatedTopicParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMsgVpnReplicatedTopicParamsWithHTTPClient(client *http.Client) *GetMsgVpnReplicatedTopicParams {
	var ()
	return &GetMsgVpnReplicatedTopicParams{
		HTTPClient: client,
	}
}

/*GetMsgVpnReplicatedTopicParams contains all the parameters to send to the API endpoint
for the get msg vpn replicated topic operation typically these are written to a http.Request
*/
type GetMsgVpnReplicatedTopicParams struct {

	/*MsgVpnName
	  The name of the Message VPN.

	*/
	MsgVpnName string
	/*ReplicatedTopic
	  The topic for applying replication. Published messages matching this topic will be replicated to the standby site.

	*/
	ReplicatedTopic string
	/*Select
	  Include in the response only selected attributes of the object, or exclude from the response selected attributes of the object. See the documentation for the `select` parameter.

	*/
	Select []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get msg vpn replicated topic params
func (o *GetMsgVpnReplicatedTopicParams) WithTimeout(timeout time.Duration) *GetMsgVpnReplicatedTopicParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get msg vpn replicated topic params
func (o *GetMsgVpnReplicatedTopicParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get msg vpn replicated topic params
func (o *GetMsgVpnReplicatedTopicParams) WithContext(ctx context.Context) *GetMsgVpnReplicatedTopicParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get msg vpn replicated topic params
func (o *GetMsgVpnReplicatedTopicParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get msg vpn replicated topic params
func (o *GetMsgVpnReplicatedTopicParams) WithHTTPClient(client *http.Client) *GetMsgVpnReplicatedTopicParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get msg vpn replicated topic params
func (o *GetMsgVpnReplicatedTopicParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMsgVpnName adds the msgVpnName to the get msg vpn replicated topic params
func (o *GetMsgVpnReplicatedTopicParams) WithMsgVpnName(msgVpnName string) *GetMsgVpnReplicatedTopicParams {
	o.SetMsgVpnName(msgVpnName)
	return o
}

// SetMsgVpnName adds the msgVpnName to the get msg vpn replicated topic params
func (o *GetMsgVpnReplicatedTopicParams) SetMsgVpnName(msgVpnName string) {
	o.MsgVpnName = msgVpnName
}

// WithReplicatedTopic adds the replicatedTopic to the get msg vpn replicated topic params
func (o *GetMsgVpnReplicatedTopicParams) WithReplicatedTopic(replicatedTopic string) *GetMsgVpnReplicatedTopicParams {
	o.SetReplicatedTopic(replicatedTopic)
	return o
}

// SetReplicatedTopic adds the replicatedTopic to the get msg vpn replicated topic params
func (o *GetMsgVpnReplicatedTopicParams) SetReplicatedTopic(replicatedTopic string) {
	o.ReplicatedTopic = replicatedTopic
}

// WithSelect adds the selectVar to the get msg vpn replicated topic params
func (o *GetMsgVpnReplicatedTopicParams) WithSelect(selectVar []string) *GetMsgVpnReplicatedTopicParams {
	o.SetSelect(selectVar)
	return o
}

// SetSelect adds the select to the get msg vpn replicated topic params
func (o *GetMsgVpnReplicatedTopicParams) SetSelect(selectVar []string) {
	o.Select = selectVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetMsgVpnReplicatedTopicParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param msgVpnName
	if err := r.SetPathParam("msgVpnName", o.MsgVpnName); err != nil {
		return err
	}

	// path param replicatedTopic
	if err := r.SetPathParam("replicatedTopic", o.ReplicatedTopic); err != nil {
		return err
	}

	valuesSelect := o.Select

	joinedSelect := swag.JoinByFormat(valuesSelect, "csv")
	// query array param select
	if err := r.SetQueryParam("select", joinedSelect...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
