// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMsgVpnACLProfileClientConnectExceptionParams creates a new GetMsgVpnACLProfileClientConnectExceptionParams object
// with the default values initialized.
func NewGetMsgVpnACLProfileClientConnectExceptionParams() *GetMsgVpnACLProfileClientConnectExceptionParams {
	var ()
	return &GetMsgVpnACLProfileClientConnectExceptionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMsgVpnACLProfileClientConnectExceptionParamsWithTimeout creates a new GetMsgVpnACLProfileClientConnectExceptionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMsgVpnACLProfileClientConnectExceptionParamsWithTimeout(timeout time.Duration) *GetMsgVpnACLProfileClientConnectExceptionParams {
	var ()
	return &GetMsgVpnACLProfileClientConnectExceptionParams{

		timeout: timeout,
	}
}

// NewGetMsgVpnACLProfileClientConnectExceptionParamsWithContext creates a new GetMsgVpnACLProfileClientConnectExceptionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMsgVpnACLProfileClientConnectExceptionParamsWithContext(ctx context.Context) *GetMsgVpnACLProfileClientConnectExceptionParams {
	var ()
	return &GetMsgVpnACLProfileClientConnectExceptionParams{

		Context: ctx,
	}
}

// NewGetMsgVpnACLProfileClientConnectExceptionParamsWithHTTPClient creates a new GetMsgVpnACLProfileClientConnectExceptionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMsgVpnACLProfileClientConnectExceptionParamsWithHTTPClient(client *http.Client) *GetMsgVpnACLProfileClientConnectExceptionParams {
	var ()
	return &GetMsgVpnACLProfileClientConnectExceptionParams{
		HTTPClient: client,
	}
}

/*GetMsgVpnACLProfileClientConnectExceptionParams contains all the parameters to send to the API endpoint
for the get msg vpn Acl profile client connect exception operation typically these are written to a http.Request
*/
type GetMsgVpnACLProfileClientConnectExceptionParams struct {

	/*ACLProfileName
	  The name of the ACL Profile.

	*/
	ACLProfileName string
	/*ClientConnectExceptionAddress
	  The IP address/netmask of the client connect exception in CIDR form.

	*/
	ClientConnectExceptionAddress string
	/*MsgVpnName
	  The name of the Message VPN.

	*/
	MsgVpnName string
	/*Select
	  Include in the response only selected attributes of the object, or exclude from the response selected attributes of the object. See the documentation for the `select` parameter.

	*/
	Select []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get msg vpn Acl profile client connect exception params
func (o *GetMsgVpnACLProfileClientConnectExceptionParams) WithTimeout(timeout time.Duration) *GetMsgVpnACLProfileClientConnectExceptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get msg vpn Acl profile client connect exception params
func (o *GetMsgVpnACLProfileClientConnectExceptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get msg vpn Acl profile client connect exception params
func (o *GetMsgVpnACLProfileClientConnectExceptionParams) WithContext(ctx context.Context) *GetMsgVpnACLProfileClientConnectExceptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get msg vpn Acl profile client connect exception params
func (o *GetMsgVpnACLProfileClientConnectExceptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get msg vpn Acl profile client connect exception params
func (o *GetMsgVpnACLProfileClientConnectExceptionParams) WithHTTPClient(client *http.Client) *GetMsgVpnACLProfileClientConnectExceptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get msg vpn Acl profile client connect exception params
func (o *GetMsgVpnACLProfileClientConnectExceptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithACLProfileName adds the aCLProfileName to the get msg vpn Acl profile client connect exception params
func (o *GetMsgVpnACLProfileClientConnectExceptionParams) WithACLProfileName(aCLProfileName string) *GetMsgVpnACLProfileClientConnectExceptionParams {
	o.SetACLProfileName(aCLProfileName)
	return o
}

// SetACLProfileName adds the aclProfileName to the get msg vpn Acl profile client connect exception params
func (o *GetMsgVpnACLProfileClientConnectExceptionParams) SetACLProfileName(aCLProfileName string) {
	o.ACLProfileName = aCLProfileName
}

// WithClientConnectExceptionAddress adds the clientConnectExceptionAddress to the get msg vpn Acl profile client connect exception params
func (o *GetMsgVpnACLProfileClientConnectExceptionParams) WithClientConnectExceptionAddress(clientConnectExceptionAddress string) *GetMsgVpnACLProfileClientConnectExceptionParams {
	o.SetClientConnectExceptionAddress(clientConnectExceptionAddress)
	return o
}

// SetClientConnectExceptionAddress adds the clientConnectExceptionAddress to the get msg vpn Acl profile client connect exception params
func (o *GetMsgVpnACLProfileClientConnectExceptionParams) SetClientConnectExceptionAddress(clientConnectExceptionAddress string) {
	o.ClientConnectExceptionAddress = clientConnectExceptionAddress
}

// WithMsgVpnName adds the msgVpnName to the get msg vpn Acl profile client connect exception params
func (o *GetMsgVpnACLProfileClientConnectExceptionParams) WithMsgVpnName(msgVpnName string) *GetMsgVpnACLProfileClientConnectExceptionParams {
	o.SetMsgVpnName(msgVpnName)
	return o
}

// SetMsgVpnName adds the msgVpnName to the get msg vpn Acl profile client connect exception params
func (o *GetMsgVpnACLProfileClientConnectExceptionParams) SetMsgVpnName(msgVpnName string) {
	o.MsgVpnName = msgVpnName
}

// WithSelect adds the selectVar to the get msg vpn Acl profile client connect exception params
func (o *GetMsgVpnACLProfileClientConnectExceptionParams) WithSelect(selectVar []string) *GetMsgVpnACLProfileClientConnectExceptionParams {
	o.SetSelect(selectVar)
	return o
}

// SetSelect adds the select to the get msg vpn Acl profile client connect exception params
func (o *GetMsgVpnACLProfileClientConnectExceptionParams) SetSelect(selectVar []string) {
	o.Select = selectVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetMsgVpnACLProfileClientConnectExceptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param aclProfileName
	if err := r.SetPathParam("aclProfileName", o.ACLProfileName); err != nil {
		return err
	}

	// path param clientConnectExceptionAddress
	if err := r.SetPathParam("clientConnectExceptionAddress", o.ClientConnectExceptionAddress); err != nil {
		return err
	}

	// path param msgVpnName
	if err := r.SetPathParam("msgVpnName", o.MsgVpnName); err != nil {
		return err
	}

	valuesSelect := o.Select

	joinedSelect := swag.JoinByFormat(valuesSelect, "csv")
	// query array param select
	if err := r.SetQueryParam("select", joinedSelect...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
