// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMsgVpnBridgeParams creates a new GetMsgVpnBridgeParams object
// with the default values initialized.
func NewGetMsgVpnBridgeParams() *GetMsgVpnBridgeParams {
	var ()
	return &GetMsgVpnBridgeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMsgVpnBridgeParamsWithTimeout creates a new GetMsgVpnBridgeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMsgVpnBridgeParamsWithTimeout(timeout time.Duration) *GetMsgVpnBridgeParams {
	var ()
	return &GetMsgVpnBridgeParams{

		timeout: timeout,
	}
}

// NewGetMsgVpnBridgeParamsWithContext creates a new GetMsgVpnBridgeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMsgVpnBridgeParamsWithContext(ctx context.Context) *GetMsgVpnBridgeParams {
	var ()
	return &GetMsgVpnBridgeParams{

		Context: ctx,
	}
}

// NewGetMsgVpnBridgeParamsWithHTTPClient creates a new GetMsgVpnBridgeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMsgVpnBridgeParamsWithHTTPClient(client *http.Client) *GetMsgVpnBridgeParams {
	var ()
	return &GetMsgVpnBridgeParams{
		HTTPClient: client,
	}
}

/*GetMsgVpnBridgeParams contains all the parameters to send to the API endpoint
for the get msg vpn bridge operation typically these are written to a http.Request
*/
type GetMsgVpnBridgeParams struct {

	/*BridgeName
	  The name of the Bridge.

	*/
	BridgeName string
	/*BridgeVirtualRouter
	  The virtual router of the Bridge.

	*/
	BridgeVirtualRouter string
	/*MsgVpnName
	  The name of the Message VPN.

	*/
	MsgVpnName string
	/*Select
	  Include in the response only selected attributes of the object, or exclude from the response selected attributes of the object. See the documentation for the `select` parameter.

	*/
	Select []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get msg vpn bridge params
func (o *GetMsgVpnBridgeParams) WithTimeout(timeout time.Duration) *GetMsgVpnBridgeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get msg vpn bridge params
func (o *GetMsgVpnBridgeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get msg vpn bridge params
func (o *GetMsgVpnBridgeParams) WithContext(ctx context.Context) *GetMsgVpnBridgeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get msg vpn bridge params
func (o *GetMsgVpnBridgeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get msg vpn bridge params
func (o *GetMsgVpnBridgeParams) WithHTTPClient(client *http.Client) *GetMsgVpnBridgeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get msg vpn bridge params
func (o *GetMsgVpnBridgeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBridgeName adds the bridgeName to the get msg vpn bridge params
func (o *GetMsgVpnBridgeParams) WithBridgeName(bridgeName string) *GetMsgVpnBridgeParams {
	o.SetBridgeName(bridgeName)
	return o
}

// SetBridgeName adds the bridgeName to the get msg vpn bridge params
func (o *GetMsgVpnBridgeParams) SetBridgeName(bridgeName string) {
	o.BridgeName = bridgeName
}

// WithBridgeVirtualRouter adds the bridgeVirtualRouter to the get msg vpn bridge params
func (o *GetMsgVpnBridgeParams) WithBridgeVirtualRouter(bridgeVirtualRouter string) *GetMsgVpnBridgeParams {
	o.SetBridgeVirtualRouter(bridgeVirtualRouter)
	return o
}

// SetBridgeVirtualRouter adds the bridgeVirtualRouter to the get msg vpn bridge params
func (o *GetMsgVpnBridgeParams) SetBridgeVirtualRouter(bridgeVirtualRouter string) {
	o.BridgeVirtualRouter = bridgeVirtualRouter
}

// WithMsgVpnName adds the msgVpnName to the get msg vpn bridge params
func (o *GetMsgVpnBridgeParams) WithMsgVpnName(msgVpnName string) *GetMsgVpnBridgeParams {
	o.SetMsgVpnName(msgVpnName)
	return o
}

// SetMsgVpnName adds the msgVpnName to the get msg vpn bridge params
func (o *GetMsgVpnBridgeParams) SetMsgVpnName(msgVpnName string) {
	o.MsgVpnName = msgVpnName
}

// WithSelect adds the selectVar to the get msg vpn bridge params
func (o *GetMsgVpnBridgeParams) WithSelect(selectVar []string) *GetMsgVpnBridgeParams {
	o.SetSelect(selectVar)
	return o
}

// SetSelect adds the select to the get msg vpn bridge params
func (o *GetMsgVpnBridgeParams) SetSelect(selectVar []string) {
	o.Select = selectVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetMsgVpnBridgeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param bridgeName
	if err := r.SetPathParam("bridgeName", o.BridgeName); err != nil {
		return err
	}

	// path param bridgeVirtualRouter
	if err := r.SetPathParam("bridgeVirtualRouter", o.BridgeVirtualRouter); err != nil {
		return err
	}

	// path param msgVpnName
	if err := r.SetPathParam("msgVpnName", o.MsgVpnName); err != nil {
		return err
	}

	valuesSelect := o.Select

	joinedSelect := swag.JoinByFormat(valuesSelect, "csv")
	// query array param select
	if err := r.SetQueryParam("select", joinedSelect...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
