// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// GetMsgVpnACLProfileSubscribeExceptionsReader is a Reader for the GetMsgVpnACLProfileSubscribeExceptions structure.
type GetMsgVpnACLProfileSubscribeExceptionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMsgVpnACLProfileSubscribeExceptionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMsgVpnACLProfileSubscribeExceptionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetMsgVpnACLProfileSubscribeExceptionsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetMsgVpnACLProfileSubscribeExceptionsOK creates a GetMsgVpnACLProfileSubscribeExceptionsOK with default headers values
func NewGetMsgVpnACLProfileSubscribeExceptionsOK() *GetMsgVpnACLProfileSubscribeExceptionsOK {
	return &GetMsgVpnACLProfileSubscribeExceptionsOK{}
}

/*GetMsgVpnACLProfileSubscribeExceptionsOK handles this case with default header values.

The list of Subscribe Topic Exception objects' attributes, and the request metadata.
*/
type GetMsgVpnACLProfileSubscribeExceptionsOK struct {
	Payload *models.MsgVpnACLProfileSubscribeExceptionsResponse
}

func (o *GetMsgVpnACLProfileSubscribeExceptionsOK) Error() string {
	return fmt.Sprintf("[GET /msgVpns/{msgVpnName}/aclProfiles/{aclProfileName}/subscribeExceptions][%d] getMsgVpnAclProfileSubscribeExceptionsOK  %+v", 200, o.Payload)
}

func (o *GetMsgVpnACLProfileSubscribeExceptionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MsgVpnACLProfileSubscribeExceptionsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMsgVpnACLProfileSubscribeExceptionsDefault creates a GetMsgVpnACLProfileSubscribeExceptionsDefault with default headers values
func NewGetMsgVpnACLProfileSubscribeExceptionsDefault(code int) *GetMsgVpnACLProfileSubscribeExceptionsDefault {
	return &GetMsgVpnACLProfileSubscribeExceptionsDefault{
		_statusCode: code,
	}
}

/*GetMsgVpnACLProfileSubscribeExceptionsDefault handles this case with default header values.

The error response.
*/
type GetMsgVpnACLProfileSubscribeExceptionsDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the get msg vpn Acl profile subscribe exceptions default response
func (o *GetMsgVpnACLProfileSubscribeExceptionsDefault) Code() int {
	return o._statusCode
}

func (o *GetMsgVpnACLProfileSubscribeExceptionsDefault) Error() string {
	return fmt.Sprintf("[GET /msgVpns/{msgVpnName}/aclProfiles/{aclProfileName}/subscribeExceptions][%d] getMsgVpnAclProfileSubscribeExceptions default  %+v", o._statusCode, o.Payload)
}

func (o *GetMsgVpnACLProfileSubscribeExceptionsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
