// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// GetMsgVpnAuthorizationGroupsReader is a Reader for the GetMsgVpnAuthorizationGroups structure.
type GetMsgVpnAuthorizationGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMsgVpnAuthorizationGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMsgVpnAuthorizationGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetMsgVpnAuthorizationGroupsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetMsgVpnAuthorizationGroupsOK creates a GetMsgVpnAuthorizationGroupsOK with default headers values
func NewGetMsgVpnAuthorizationGroupsOK() *GetMsgVpnAuthorizationGroupsOK {
	return &GetMsgVpnAuthorizationGroupsOK{}
}

/*GetMsgVpnAuthorizationGroupsOK handles this case with default header values.

The list of LDAP Authorization Group objects' attributes, and the request metadata.
*/
type GetMsgVpnAuthorizationGroupsOK struct {
	Payload *models.MsgVpnAuthorizationGroupsResponse
}

func (o *GetMsgVpnAuthorizationGroupsOK) Error() string {
	return fmt.Sprintf("[GET /msgVpns/{msgVpnName}/authorizationGroups][%d] getMsgVpnAuthorizationGroupsOK  %+v", 200, o.Payload)
}

func (o *GetMsgVpnAuthorizationGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MsgVpnAuthorizationGroupsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMsgVpnAuthorizationGroupsDefault creates a GetMsgVpnAuthorizationGroupsDefault with default headers values
func NewGetMsgVpnAuthorizationGroupsDefault(code int) *GetMsgVpnAuthorizationGroupsDefault {
	return &GetMsgVpnAuthorizationGroupsDefault{
		_statusCode: code,
	}
}

/*GetMsgVpnAuthorizationGroupsDefault handles this case with default header values.

The error response.
*/
type GetMsgVpnAuthorizationGroupsDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the get msg vpn authorization groups default response
func (o *GetMsgVpnAuthorizationGroupsDefault) Code() int {
	return o._statusCode
}

func (o *GetMsgVpnAuthorizationGroupsDefault) Error() string {
	return fmt.Sprintf("[GET /msgVpns/{msgVpnName}/authorizationGroups][%d] getMsgVpnAuthorizationGroups default  %+v", o._statusCode, o.Payload)
}

func (o *GetMsgVpnAuthorizationGroupsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
