// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMsgVpnJndiConnectionFactoriesParams creates a new GetMsgVpnJndiConnectionFactoriesParams object
// with the default values initialized.
func NewGetMsgVpnJndiConnectionFactoriesParams() *GetMsgVpnJndiConnectionFactoriesParams {
	var (
		countDefault = int64(10)
	)
	return &GetMsgVpnJndiConnectionFactoriesParams{
		Count: &countDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMsgVpnJndiConnectionFactoriesParamsWithTimeout creates a new GetMsgVpnJndiConnectionFactoriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMsgVpnJndiConnectionFactoriesParamsWithTimeout(timeout time.Duration) *GetMsgVpnJndiConnectionFactoriesParams {
	var (
		countDefault = int64(10)
	)
	return &GetMsgVpnJndiConnectionFactoriesParams{
		Count: &countDefault,

		timeout: timeout,
	}
}

// NewGetMsgVpnJndiConnectionFactoriesParamsWithContext creates a new GetMsgVpnJndiConnectionFactoriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMsgVpnJndiConnectionFactoriesParamsWithContext(ctx context.Context) *GetMsgVpnJndiConnectionFactoriesParams {
	var (
		countDefault = int64(10)
	)
	return &GetMsgVpnJndiConnectionFactoriesParams{
		Count: &countDefault,

		Context: ctx,
	}
}

// NewGetMsgVpnJndiConnectionFactoriesParamsWithHTTPClient creates a new GetMsgVpnJndiConnectionFactoriesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMsgVpnJndiConnectionFactoriesParamsWithHTTPClient(client *http.Client) *GetMsgVpnJndiConnectionFactoriesParams {
	var (
		countDefault = int64(10)
	)
	return &GetMsgVpnJndiConnectionFactoriesParams{
		Count:      &countDefault,
		HTTPClient: client,
	}
}

/*GetMsgVpnJndiConnectionFactoriesParams contains all the parameters to send to the API endpoint
for the get msg vpn jndi connection factories operation typically these are written to a http.Request
*/
type GetMsgVpnJndiConnectionFactoriesParams struct {

	/*Count
	  Limit the count of objects in the response. See the documentation for the `count` parameter.

	*/
	Count *int64
	/*Cursor
	  The cursor, or position, for the next page of objects. See the documentation for the `cursor` parameter.

	*/
	Cursor *string
	/*MsgVpnName
	  The name of the Message VPN.

	*/
	MsgVpnName string
	/*Select
	  Include in the response only selected attributes of the object, or exclude from the response selected attributes of the object. See the documentation for the `select` parameter.

	*/
	Select []string
	/*Where
	  Include in the response only objects where certain conditions are true. See the the documentation for the `where` parameter.

	*/
	Where []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get msg vpn jndi connection factories params
func (o *GetMsgVpnJndiConnectionFactoriesParams) WithTimeout(timeout time.Duration) *GetMsgVpnJndiConnectionFactoriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get msg vpn jndi connection factories params
func (o *GetMsgVpnJndiConnectionFactoriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get msg vpn jndi connection factories params
func (o *GetMsgVpnJndiConnectionFactoriesParams) WithContext(ctx context.Context) *GetMsgVpnJndiConnectionFactoriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get msg vpn jndi connection factories params
func (o *GetMsgVpnJndiConnectionFactoriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get msg vpn jndi connection factories params
func (o *GetMsgVpnJndiConnectionFactoriesParams) WithHTTPClient(client *http.Client) *GetMsgVpnJndiConnectionFactoriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get msg vpn jndi connection factories params
func (o *GetMsgVpnJndiConnectionFactoriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCount adds the count to the get msg vpn jndi connection factories params
func (o *GetMsgVpnJndiConnectionFactoriesParams) WithCount(count *int64) *GetMsgVpnJndiConnectionFactoriesParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the get msg vpn jndi connection factories params
func (o *GetMsgVpnJndiConnectionFactoriesParams) SetCount(count *int64) {
	o.Count = count
}

// WithCursor adds the cursor to the get msg vpn jndi connection factories params
func (o *GetMsgVpnJndiConnectionFactoriesParams) WithCursor(cursor *string) *GetMsgVpnJndiConnectionFactoriesParams {
	o.SetCursor(cursor)
	return o
}

// SetCursor adds the cursor to the get msg vpn jndi connection factories params
func (o *GetMsgVpnJndiConnectionFactoriesParams) SetCursor(cursor *string) {
	o.Cursor = cursor
}

// WithMsgVpnName adds the msgVpnName to the get msg vpn jndi connection factories params
func (o *GetMsgVpnJndiConnectionFactoriesParams) WithMsgVpnName(msgVpnName string) *GetMsgVpnJndiConnectionFactoriesParams {
	o.SetMsgVpnName(msgVpnName)
	return o
}

// SetMsgVpnName adds the msgVpnName to the get msg vpn jndi connection factories params
func (o *GetMsgVpnJndiConnectionFactoriesParams) SetMsgVpnName(msgVpnName string) {
	o.MsgVpnName = msgVpnName
}

// WithSelect adds the selectVar to the get msg vpn jndi connection factories params
func (o *GetMsgVpnJndiConnectionFactoriesParams) WithSelect(selectVar []string) *GetMsgVpnJndiConnectionFactoriesParams {
	o.SetSelect(selectVar)
	return o
}

// SetSelect adds the select to the get msg vpn jndi connection factories params
func (o *GetMsgVpnJndiConnectionFactoriesParams) SetSelect(selectVar []string) {
	o.Select = selectVar
}

// WithWhere adds the where to the get msg vpn jndi connection factories params
func (o *GetMsgVpnJndiConnectionFactoriesParams) WithWhere(where []string) *GetMsgVpnJndiConnectionFactoriesParams {
	o.SetWhere(where)
	return o
}

// SetWhere adds the where to the get msg vpn jndi connection factories params
func (o *GetMsgVpnJndiConnectionFactoriesParams) SetWhere(where []string) {
	o.Where = where
}

// WriteToRequest writes these params to a swagger request
func (o *GetMsgVpnJndiConnectionFactoriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Count != nil {

		// query param count
		var qrCount int64
		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatInt64(qrCount)
		if qCount != "" {
			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}

	}

	if o.Cursor != nil {

		// query param cursor
		var qrCursor string
		if o.Cursor != nil {
			qrCursor = *o.Cursor
		}
		qCursor := qrCursor
		if qCursor != "" {
			if err := r.SetQueryParam("cursor", qCursor); err != nil {
				return err
			}
		}

	}

	// path param msgVpnName
	if err := r.SetPathParam("msgVpnName", o.MsgVpnName); err != nil {
		return err
	}

	valuesSelect := o.Select

	joinedSelect := swag.JoinByFormat(valuesSelect, "csv")
	// query array param select
	if err := r.SetQueryParam("select", joinedSelect...); err != nil {
		return err
	}

	valuesWhere := o.Where

	joinedWhere := swag.JoinByFormat(valuesWhere, "csv")
	// query array param where
	if err := r.SetQueryParam("where", joinedWhere...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
