// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// GetMsgVpnRestDeliveryPointsReader is a Reader for the GetMsgVpnRestDeliveryPoints structure.
type GetMsgVpnRestDeliveryPointsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMsgVpnRestDeliveryPointsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMsgVpnRestDeliveryPointsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetMsgVpnRestDeliveryPointsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetMsgVpnRestDeliveryPointsOK creates a GetMsgVpnRestDeliveryPointsOK with default headers values
func NewGetMsgVpnRestDeliveryPointsOK() *GetMsgVpnRestDeliveryPointsOK {
	return &GetMsgVpnRestDeliveryPointsOK{}
}

/*GetMsgVpnRestDeliveryPointsOK handles this case with default header values.

The list of REST Delivery Point objects' attributes, and the request metadata.
*/
type GetMsgVpnRestDeliveryPointsOK struct {
	Payload *models.MsgVpnRestDeliveryPointsResponse
}

func (o *GetMsgVpnRestDeliveryPointsOK) Error() string {
	return fmt.Sprintf("[GET /msgVpns/{msgVpnName}/restDeliveryPoints][%d] getMsgVpnRestDeliveryPointsOK  %+v", 200, o.Payload)
}

func (o *GetMsgVpnRestDeliveryPointsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MsgVpnRestDeliveryPointsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMsgVpnRestDeliveryPointsDefault creates a GetMsgVpnRestDeliveryPointsDefault with default headers values
func NewGetMsgVpnRestDeliveryPointsDefault(code int) *GetMsgVpnRestDeliveryPointsDefault {
	return &GetMsgVpnRestDeliveryPointsDefault{
		_statusCode: code,
	}
}

/*GetMsgVpnRestDeliveryPointsDefault handles this case with default header values.

Error response
*/
type GetMsgVpnRestDeliveryPointsDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the get msg vpn rest delivery points default response
func (o *GetMsgVpnRestDeliveryPointsDefault) Code() int {
	return o._statusCode
}

func (o *GetMsgVpnRestDeliveryPointsDefault) Error() string {
	return fmt.Sprintf("[GET /msgVpns/{msgVpnName}/restDeliveryPoints][%d] getMsgVpnRestDeliveryPoints default  %+v", o._statusCode, o.Payload)
}

func (o *GetMsgVpnRestDeliveryPointsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
