// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// GetMsgVpnACLProfileSubscribeExceptionReader is a Reader for the GetMsgVpnACLProfileSubscribeException structure.
type GetMsgVpnACLProfileSubscribeExceptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMsgVpnACLProfileSubscribeExceptionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMsgVpnACLProfileSubscribeExceptionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetMsgVpnACLProfileSubscribeExceptionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetMsgVpnACLProfileSubscribeExceptionOK creates a GetMsgVpnACLProfileSubscribeExceptionOK with default headers values
func NewGetMsgVpnACLProfileSubscribeExceptionOK() *GetMsgVpnACLProfileSubscribeExceptionOK {
	return &GetMsgVpnACLProfileSubscribeExceptionOK{}
}

/*GetMsgVpnACLProfileSubscribeExceptionOK handles this case with default header values.

The Subscribe Topic Exception object's attributes, and the request metadata.
*/
type GetMsgVpnACLProfileSubscribeExceptionOK struct {
	Payload *models.MsgVpnACLProfileSubscribeExceptionResponse
}

func (o *GetMsgVpnACLProfileSubscribeExceptionOK) Error() string {
	return fmt.Sprintf("[GET /msgVpns/{msgVpnName}/aclProfiles/{aclProfileName}/subscribeExceptions/{topicSyntax},{subscribeExceptionTopic}][%d] getMsgVpnAclProfileSubscribeExceptionOK  %+v", 200, o.Payload)
}

func (o *GetMsgVpnACLProfileSubscribeExceptionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MsgVpnACLProfileSubscribeExceptionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMsgVpnACLProfileSubscribeExceptionDefault creates a GetMsgVpnACLProfileSubscribeExceptionDefault with default headers values
func NewGetMsgVpnACLProfileSubscribeExceptionDefault(code int) *GetMsgVpnACLProfileSubscribeExceptionDefault {
	return &GetMsgVpnACLProfileSubscribeExceptionDefault{
		_statusCode: code,
	}
}

/*GetMsgVpnACLProfileSubscribeExceptionDefault handles this case with default header values.

The error response.
*/
type GetMsgVpnACLProfileSubscribeExceptionDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the get msg vpn Acl profile subscribe exception default response
func (o *GetMsgVpnACLProfileSubscribeExceptionDefault) Code() int {
	return o._statusCode
}

func (o *GetMsgVpnACLProfileSubscribeExceptionDefault) Error() string {
	return fmt.Sprintf("[GET /msgVpns/{msgVpnName}/aclProfiles/{aclProfileName}/subscribeExceptions/{topicSyntax},{subscribeExceptionTopic}][%d] getMsgVpnAclProfileSubscribeException default  %+v", o._statusCode, o.Payload)
}

func (o *GetMsgVpnACLProfileSubscribeExceptionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
