// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// ReplaceMsgVpnRestDeliveryPointRestConsumerReader is a Reader for the ReplaceMsgVpnRestDeliveryPointRestConsumer structure.
type ReplaceMsgVpnRestDeliveryPointRestConsumerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplaceMsgVpnRestDeliveryPointRestConsumerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewReplaceMsgVpnRestDeliveryPointRestConsumerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewReplaceMsgVpnRestDeliveryPointRestConsumerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewReplaceMsgVpnRestDeliveryPointRestConsumerOK creates a ReplaceMsgVpnRestDeliveryPointRestConsumerOK with default headers values
func NewReplaceMsgVpnRestDeliveryPointRestConsumerOK() *ReplaceMsgVpnRestDeliveryPointRestConsumerOK {
	return &ReplaceMsgVpnRestDeliveryPointRestConsumerOK{}
}

/*ReplaceMsgVpnRestDeliveryPointRestConsumerOK handles this case with default header values.

The REST Consumer object's attributes after being replaced, and the request metadata.
*/
type ReplaceMsgVpnRestDeliveryPointRestConsumerOK struct {
	Payload *models.MsgVpnRestDeliveryPointRestConsumerResponse
}

func (o *ReplaceMsgVpnRestDeliveryPointRestConsumerOK) Error() string {
	return fmt.Sprintf("[PUT /msgVpns/{msgVpnName}/restDeliveryPoints/{restDeliveryPointName}/restConsumers/{restConsumerName}][%d] replaceMsgVpnRestDeliveryPointRestConsumerOK  %+v", 200, o.Payload)
}

func (o *ReplaceMsgVpnRestDeliveryPointRestConsumerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MsgVpnRestDeliveryPointRestConsumerResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceMsgVpnRestDeliveryPointRestConsumerDefault creates a ReplaceMsgVpnRestDeliveryPointRestConsumerDefault with default headers values
func NewReplaceMsgVpnRestDeliveryPointRestConsumerDefault(code int) *ReplaceMsgVpnRestDeliveryPointRestConsumerDefault {
	return &ReplaceMsgVpnRestDeliveryPointRestConsumerDefault{
		_statusCode: code,
	}
}

/*ReplaceMsgVpnRestDeliveryPointRestConsumerDefault handles this case with default header values.

The error response.
*/
type ReplaceMsgVpnRestDeliveryPointRestConsumerDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the replace msg vpn rest delivery point rest consumer default response
func (o *ReplaceMsgVpnRestDeliveryPointRestConsumerDefault) Code() int {
	return o._statusCode
}

func (o *ReplaceMsgVpnRestDeliveryPointRestConsumerDefault) Error() string {
	return fmt.Sprintf("[PUT /msgVpns/{msgVpnName}/restDeliveryPoints/{restDeliveryPointName}/restConsumers/{restConsumerName}][%d] replaceMsgVpnRestDeliveryPointRestConsumer default  %+v", o._statusCode, o.Payload)
}

func (o *ReplaceMsgVpnRestDeliveryPointRestConsumerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
