// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// ReplaceMsgVpnClientProfileReader is a Reader for the ReplaceMsgVpnClientProfile structure.
type ReplaceMsgVpnClientProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplaceMsgVpnClientProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewReplaceMsgVpnClientProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewReplaceMsgVpnClientProfileDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewReplaceMsgVpnClientProfileOK creates a ReplaceMsgVpnClientProfileOK with default headers values
func NewReplaceMsgVpnClientProfileOK() *ReplaceMsgVpnClientProfileOK {
	return &ReplaceMsgVpnClientProfileOK{}
}

/*ReplaceMsgVpnClientProfileOK handles this case with default header values.

The Client Profile object's attributes after being replaced, and the request metadata.
*/
type ReplaceMsgVpnClientProfileOK struct {
	Payload *models.MsgVpnClientProfileResponse
}

func (o *ReplaceMsgVpnClientProfileOK) Error() string {
	return fmt.Sprintf("[PUT /msgVpns/{msgVpnName}/clientProfiles/{clientProfileName}][%d] replaceMsgVpnClientProfileOK  %+v", 200, o.Payload)
}

func (o *ReplaceMsgVpnClientProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MsgVpnClientProfileResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceMsgVpnClientProfileDefault creates a ReplaceMsgVpnClientProfileDefault with default headers values
func NewReplaceMsgVpnClientProfileDefault(code int) *ReplaceMsgVpnClientProfileDefault {
	return &ReplaceMsgVpnClientProfileDefault{
		_statusCode: code,
	}
}

/*ReplaceMsgVpnClientProfileDefault handles this case with default header values.

The error response.
*/
type ReplaceMsgVpnClientProfileDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the replace msg vpn client profile default response
func (o *ReplaceMsgVpnClientProfileDefault) Code() int {
	return o._statusCode
}

func (o *ReplaceMsgVpnClientProfileDefault) Error() string {
	return fmt.Sprintf("[PUT /msgVpns/{msgVpnName}/clientProfiles/{clientProfileName}][%d] replaceMsgVpnClientProfile default  %+v", o._statusCode, o.Payload)
}

func (o *ReplaceMsgVpnClientProfileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
