// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// NewReplaceMsgVpnReplicatedTopicParams creates a new ReplaceMsgVpnReplicatedTopicParams object
// with the default values initialized.
func NewReplaceMsgVpnReplicatedTopicParams() *ReplaceMsgVpnReplicatedTopicParams {
	var ()
	return &ReplaceMsgVpnReplicatedTopicParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReplaceMsgVpnReplicatedTopicParamsWithTimeout creates a new ReplaceMsgVpnReplicatedTopicParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReplaceMsgVpnReplicatedTopicParamsWithTimeout(timeout time.Duration) *ReplaceMsgVpnReplicatedTopicParams {
	var ()
	return &ReplaceMsgVpnReplicatedTopicParams{

		timeout: timeout,
	}
}

// NewReplaceMsgVpnReplicatedTopicParamsWithContext creates a new ReplaceMsgVpnReplicatedTopicParams object
// with the default values initialized, and the ability to set a context for a request
func NewReplaceMsgVpnReplicatedTopicParamsWithContext(ctx context.Context) *ReplaceMsgVpnReplicatedTopicParams {
	var ()
	return &ReplaceMsgVpnReplicatedTopicParams{

		Context: ctx,
	}
}

// NewReplaceMsgVpnReplicatedTopicParamsWithHTTPClient creates a new ReplaceMsgVpnReplicatedTopicParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReplaceMsgVpnReplicatedTopicParamsWithHTTPClient(client *http.Client) *ReplaceMsgVpnReplicatedTopicParams {
	var ()
	return &ReplaceMsgVpnReplicatedTopicParams{
		HTTPClient: client,
	}
}

/*ReplaceMsgVpnReplicatedTopicParams contains all the parameters to send to the API endpoint
for the replace msg vpn replicated topic operation typically these are written to a http.Request
*/
type ReplaceMsgVpnReplicatedTopicParams struct {

	/*Body
	  The Replicated Topic object's attributes.

	*/
	Body *models.MsgVpnReplicatedTopic
	/*MsgVpnName
	  The name of the Message VPN.

	*/
	MsgVpnName string
	/*ReplicatedTopic
	  The topic for applying replication. Published messages matching this topic will be replicated to the standby site.

	*/
	ReplicatedTopic string
	/*Select
	  Include in the response only selected attributes of the object, or exclude from the response selected attributes of the object. See the documentation for the `select` parameter.

	*/
	Select []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the replace msg vpn replicated topic params
func (o *ReplaceMsgVpnReplicatedTopicParams) WithTimeout(timeout time.Duration) *ReplaceMsgVpnReplicatedTopicParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the replace msg vpn replicated topic params
func (o *ReplaceMsgVpnReplicatedTopicParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the replace msg vpn replicated topic params
func (o *ReplaceMsgVpnReplicatedTopicParams) WithContext(ctx context.Context) *ReplaceMsgVpnReplicatedTopicParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the replace msg vpn replicated topic params
func (o *ReplaceMsgVpnReplicatedTopicParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the replace msg vpn replicated topic params
func (o *ReplaceMsgVpnReplicatedTopicParams) WithHTTPClient(client *http.Client) *ReplaceMsgVpnReplicatedTopicParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the replace msg vpn replicated topic params
func (o *ReplaceMsgVpnReplicatedTopicParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the replace msg vpn replicated topic params
func (o *ReplaceMsgVpnReplicatedTopicParams) WithBody(body *models.MsgVpnReplicatedTopic) *ReplaceMsgVpnReplicatedTopicParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the replace msg vpn replicated topic params
func (o *ReplaceMsgVpnReplicatedTopicParams) SetBody(body *models.MsgVpnReplicatedTopic) {
	o.Body = body
}

// WithMsgVpnName adds the msgVpnName to the replace msg vpn replicated topic params
func (o *ReplaceMsgVpnReplicatedTopicParams) WithMsgVpnName(msgVpnName string) *ReplaceMsgVpnReplicatedTopicParams {
	o.SetMsgVpnName(msgVpnName)
	return o
}

// SetMsgVpnName adds the msgVpnName to the replace msg vpn replicated topic params
func (o *ReplaceMsgVpnReplicatedTopicParams) SetMsgVpnName(msgVpnName string) {
	o.MsgVpnName = msgVpnName
}

// WithReplicatedTopic adds the replicatedTopic to the replace msg vpn replicated topic params
func (o *ReplaceMsgVpnReplicatedTopicParams) WithReplicatedTopic(replicatedTopic string) *ReplaceMsgVpnReplicatedTopicParams {
	o.SetReplicatedTopic(replicatedTopic)
	return o
}

// SetReplicatedTopic adds the replicatedTopic to the replace msg vpn replicated topic params
func (o *ReplaceMsgVpnReplicatedTopicParams) SetReplicatedTopic(replicatedTopic string) {
	o.ReplicatedTopic = replicatedTopic
}

// WithSelect adds the selectVar to the replace msg vpn replicated topic params
func (o *ReplaceMsgVpnReplicatedTopicParams) WithSelect(selectVar []string) *ReplaceMsgVpnReplicatedTopicParams {
	o.SetSelect(selectVar)
	return o
}

// SetSelect adds the select to the replace msg vpn replicated topic params
func (o *ReplaceMsgVpnReplicatedTopicParams) SetSelect(selectVar []string) {
	o.Select = selectVar
}

// WriteToRequest writes these params to a swagger request
func (o *ReplaceMsgVpnReplicatedTopicParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param msgVpnName
	if err := r.SetPathParam("msgVpnName", o.MsgVpnName); err != nil {
		return err
	}

	// path param replicatedTopic
	if err := r.SetPathParam("replicatedTopic", o.ReplicatedTopic); err != nil {
		return err
	}

	valuesSelect := o.Select

	joinedSelect := swag.JoinByFormat(valuesSelect, "csv")
	// query array param select
	if err := r.SetQueryParam("select", joinedSelect...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
