// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// ReplaceMsgVpnBridgeRemoteMsgVpnReader is a Reader for the ReplaceMsgVpnBridgeRemoteMsgVpn structure.
type ReplaceMsgVpnBridgeRemoteMsgVpnReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplaceMsgVpnBridgeRemoteMsgVpnReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewReplaceMsgVpnBridgeRemoteMsgVpnOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewReplaceMsgVpnBridgeRemoteMsgVpnDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewReplaceMsgVpnBridgeRemoteMsgVpnOK creates a ReplaceMsgVpnBridgeRemoteMsgVpnOK with default headers values
func NewReplaceMsgVpnBridgeRemoteMsgVpnOK() *ReplaceMsgVpnBridgeRemoteMsgVpnOK {
	return &ReplaceMsgVpnBridgeRemoteMsgVpnOK{}
}

/*ReplaceMsgVpnBridgeRemoteMsgVpnOK handles this case with default header values.

The Remote Message VPN object's attributes after being replaced, and the request metadata.
*/
type ReplaceMsgVpnBridgeRemoteMsgVpnOK struct {
	Payload *models.MsgVpnBridgeRemoteMsgVpnResponse
}

func (o *ReplaceMsgVpnBridgeRemoteMsgVpnOK) Error() string {
	return fmt.Sprintf("[PUT /msgVpns/{msgVpnName}/bridges/{bridgeName},{bridgeVirtualRouter}/remoteMsgVpns/{remoteMsgVpnName},{remoteMsgVpnLocation},{remoteMsgVpnInterface}][%d] replaceMsgVpnBridgeRemoteMsgVpnOK  %+v", 200, o.Payload)
}

func (o *ReplaceMsgVpnBridgeRemoteMsgVpnOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MsgVpnBridgeRemoteMsgVpnResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceMsgVpnBridgeRemoteMsgVpnDefault creates a ReplaceMsgVpnBridgeRemoteMsgVpnDefault with default headers values
func NewReplaceMsgVpnBridgeRemoteMsgVpnDefault(code int) *ReplaceMsgVpnBridgeRemoteMsgVpnDefault {
	return &ReplaceMsgVpnBridgeRemoteMsgVpnDefault{
		_statusCode: code,
	}
}

/*ReplaceMsgVpnBridgeRemoteMsgVpnDefault handles this case with default header values.

The error response.
*/
type ReplaceMsgVpnBridgeRemoteMsgVpnDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the replace msg vpn bridge remote msg vpn default response
func (o *ReplaceMsgVpnBridgeRemoteMsgVpnDefault) Code() int {
	return o._statusCode
}

func (o *ReplaceMsgVpnBridgeRemoteMsgVpnDefault) Error() string {
	return fmt.Sprintf("[PUT /msgVpns/{msgVpnName}/bridges/{bridgeName},{bridgeVirtualRouter}/remoteMsgVpns/{remoteMsgVpnName},{remoteMsgVpnLocation},{remoteMsgVpnInterface}][%d] replaceMsgVpnBridgeRemoteMsgVpn default  %+v", o._statusCode, o.Payload)
}

func (o *ReplaceMsgVpnBridgeRemoteMsgVpnDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
