// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// UpdateMsgVpnDistributedCacheClusterReader is a Reader for the UpdateMsgVpnDistributedCacheCluster structure.
type UpdateMsgVpnDistributedCacheClusterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateMsgVpnDistributedCacheClusterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateMsgVpnDistributedCacheClusterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewUpdateMsgVpnDistributedCacheClusterDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateMsgVpnDistributedCacheClusterOK creates a UpdateMsgVpnDistributedCacheClusterOK with default headers values
func NewUpdateMsgVpnDistributedCacheClusterOK() *UpdateMsgVpnDistributedCacheClusterOK {
	return &UpdateMsgVpnDistributedCacheClusterOK{}
}

/*UpdateMsgVpnDistributedCacheClusterOK handles this case with default header values.

The Cache Cluster object's attributes after being updated, and the request metadata.
*/
type UpdateMsgVpnDistributedCacheClusterOK struct {
	Payload *models.MsgVpnDistributedCacheClusterResponse
}

func (o *UpdateMsgVpnDistributedCacheClusterOK) Error() string {
	return fmt.Sprintf("[PATCH /msgVpns/{msgVpnName}/distributedCaches/{cacheName}/clusters/{clusterName}][%d] updateMsgVpnDistributedCacheClusterOK  %+v", 200, o.Payload)
}

func (o *UpdateMsgVpnDistributedCacheClusterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MsgVpnDistributedCacheClusterResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateMsgVpnDistributedCacheClusterDefault creates a UpdateMsgVpnDistributedCacheClusterDefault with default headers values
func NewUpdateMsgVpnDistributedCacheClusterDefault(code int) *UpdateMsgVpnDistributedCacheClusterDefault {
	return &UpdateMsgVpnDistributedCacheClusterDefault{
		_statusCode: code,
	}
}

/*UpdateMsgVpnDistributedCacheClusterDefault handles this case with default header values.

The error response.
*/
type UpdateMsgVpnDistributedCacheClusterDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the update msg vpn distributed cache cluster default response
func (o *UpdateMsgVpnDistributedCacheClusterDefault) Code() int {
	return o._statusCode
}

func (o *UpdateMsgVpnDistributedCacheClusterDefault) Error() string {
	return fmt.Sprintf("[PATCH /msgVpns/{msgVpnName}/distributedCaches/{cacheName}/clusters/{clusterName}][%d] updateMsgVpnDistributedCacheCluster default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateMsgVpnDistributedCacheClusterDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
