// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// NewUpdateMsgVpnBridgeParams creates a new UpdateMsgVpnBridgeParams object
// with the default values initialized.
func NewUpdateMsgVpnBridgeParams() *UpdateMsgVpnBridgeParams {
	var ()
	return &UpdateMsgVpnBridgeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateMsgVpnBridgeParamsWithTimeout creates a new UpdateMsgVpnBridgeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateMsgVpnBridgeParamsWithTimeout(timeout time.Duration) *UpdateMsgVpnBridgeParams {
	var ()
	return &UpdateMsgVpnBridgeParams{

		timeout: timeout,
	}
}

// NewUpdateMsgVpnBridgeParamsWithContext creates a new UpdateMsgVpnBridgeParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateMsgVpnBridgeParamsWithContext(ctx context.Context) *UpdateMsgVpnBridgeParams {
	var ()
	return &UpdateMsgVpnBridgeParams{

		Context: ctx,
	}
}

// NewUpdateMsgVpnBridgeParamsWithHTTPClient creates a new UpdateMsgVpnBridgeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateMsgVpnBridgeParamsWithHTTPClient(client *http.Client) *UpdateMsgVpnBridgeParams {
	var ()
	return &UpdateMsgVpnBridgeParams{
		HTTPClient: client,
	}
}

/*UpdateMsgVpnBridgeParams contains all the parameters to send to the API endpoint
for the update msg vpn bridge operation typically these are written to a http.Request
*/
type UpdateMsgVpnBridgeParams struct {

	/*Body
	  The Bridge object's attributes.

	*/
	Body *models.MsgVpnBridge
	/*BridgeName
	  The bridgeName of the Bridge.

	*/
	BridgeName string
	/*BridgeVirtualRouter
	  The bridgeVirtualRouter of the Bridge.

	*/
	BridgeVirtualRouter string
	/*MsgVpnName
	  The msgVpnName of the Message VPN.

	*/
	MsgVpnName string
	/*Select
	  Include in the response only selected attributes of the object, or exclude from the response selected attributes of the object. See [Select](#select "Description of the syntax of the `select` parameter").

	*/
	Select []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update msg vpn bridge params
func (o *UpdateMsgVpnBridgeParams) WithTimeout(timeout time.Duration) *UpdateMsgVpnBridgeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update msg vpn bridge params
func (o *UpdateMsgVpnBridgeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update msg vpn bridge params
func (o *UpdateMsgVpnBridgeParams) WithContext(ctx context.Context) *UpdateMsgVpnBridgeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update msg vpn bridge params
func (o *UpdateMsgVpnBridgeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update msg vpn bridge params
func (o *UpdateMsgVpnBridgeParams) WithHTTPClient(client *http.Client) *UpdateMsgVpnBridgeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update msg vpn bridge params
func (o *UpdateMsgVpnBridgeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update msg vpn bridge params
func (o *UpdateMsgVpnBridgeParams) WithBody(body *models.MsgVpnBridge) *UpdateMsgVpnBridgeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update msg vpn bridge params
func (o *UpdateMsgVpnBridgeParams) SetBody(body *models.MsgVpnBridge) {
	o.Body = body
}

// WithBridgeName adds the bridgeName to the update msg vpn bridge params
func (o *UpdateMsgVpnBridgeParams) WithBridgeName(bridgeName string) *UpdateMsgVpnBridgeParams {
	o.SetBridgeName(bridgeName)
	return o
}

// SetBridgeName adds the bridgeName to the update msg vpn bridge params
func (o *UpdateMsgVpnBridgeParams) SetBridgeName(bridgeName string) {
	o.BridgeName = bridgeName
}

// WithBridgeVirtualRouter adds the bridgeVirtualRouter to the update msg vpn bridge params
func (o *UpdateMsgVpnBridgeParams) WithBridgeVirtualRouter(bridgeVirtualRouter string) *UpdateMsgVpnBridgeParams {
	o.SetBridgeVirtualRouter(bridgeVirtualRouter)
	return o
}

// SetBridgeVirtualRouter adds the bridgeVirtualRouter to the update msg vpn bridge params
func (o *UpdateMsgVpnBridgeParams) SetBridgeVirtualRouter(bridgeVirtualRouter string) {
	o.BridgeVirtualRouter = bridgeVirtualRouter
}

// WithMsgVpnName adds the msgVpnName to the update msg vpn bridge params
func (o *UpdateMsgVpnBridgeParams) WithMsgVpnName(msgVpnName string) *UpdateMsgVpnBridgeParams {
	o.SetMsgVpnName(msgVpnName)
	return o
}

// SetMsgVpnName adds the msgVpnName to the update msg vpn bridge params
func (o *UpdateMsgVpnBridgeParams) SetMsgVpnName(msgVpnName string) {
	o.MsgVpnName = msgVpnName
}

// WithSelect adds the selectVar to the update msg vpn bridge params
func (o *UpdateMsgVpnBridgeParams) WithSelect(selectVar []string) *UpdateMsgVpnBridgeParams {
	o.SetSelect(selectVar)
	return o
}

// SetSelect adds the select to the update msg vpn bridge params
func (o *UpdateMsgVpnBridgeParams) SetSelect(selectVar []string) {
	o.Select = selectVar
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateMsgVpnBridgeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param bridgeName
	if err := r.SetPathParam("bridgeName", o.BridgeName); err != nil {
		return err
	}

	// path param bridgeVirtualRouter
	if err := r.SetPathParam("bridgeVirtualRouter", o.BridgeVirtualRouter); err != nil {
		return err
	}

	// path param msgVpnName
	if err := r.SetPathParam("msgVpnName", o.MsgVpnName); err != nil {
		return err
	}

	valuesSelect := o.Select

	joinedSelect := swag.JoinByFormat(valuesSelect, "csv")
	// query array param select
	if err := r.SetQueryParam("select", joinedSelect...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
