// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// NewUpdateMsgVpnRestDeliveryPointQueueBindingParams creates a new UpdateMsgVpnRestDeliveryPointQueueBindingParams object
// with the default values initialized.
func NewUpdateMsgVpnRestDeliveryPointQueueBindingParams() *UpdateMsgVpnRestDeliveryPointQueueBindingParams {
	var ()
	return &UpdateMsgVpnRestDeliveryPointQueueBindingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateMsgVpnRestDeliveryPointQueueBindingParamsWithTimeout creates a new UpdateMsgVpnRestDeliveryPointQueueBindingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateMsgVpnRestDeliveryPointQueueBindingParamsWithTimeout(timeout time.Duration) *UpdateMsgVpnRestDeliveryPointQueueBindingParams {
	var ()
	return &UpdateMsgVpnRestDeliveryPointQueueBindingParams{

		timeout: timeout,
	}
}

// NewUpdateMsgVpnRestDeliveryPointQueueBindingParamsWithContext creates a new UpdateMsgVpnRestDeliveryPointQueueBindingParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateMsgVpnRestDeliveryPointQueueBindingParamsWithContext(ctx context.Context) *UpdateMsgVpnRestDeliveryPointQueueBindingParams {
	var ()
	return &UpdateMsgVpnRestDeliveryPointQueueBindingParams{

		Context: ctx,
	}
}

// NewUpdateMsgVpnRestDeliveryPointQueueBindingParamsWithHTTPClient creates a new UpdateMsgVpnRestDeliveryPointQueueBindingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateMsgVpnRestDeliveryPointQueueBindingParamsWithHTTPClient(client *http.Client) *UpdateMsgVpnRestDeliveryPointQueueBindingParams {
	var ()
	return &UpdateMsgVpnRestDeliveryPointQueueBindingParams{
		HTTPClient: client,
	}
}

/*UpdateMsgVpnRestDeliveryPointQueueBindingParams contains all the parameters to send to the API endpoint
for the update msg vpn rest delivery point queue binding operation typically these are written to a http.Request
*/
type UpdateMsgVpnRestDeliveryPointQueueBindingParams struct {

	/*Body
	  The Queue Binding object's attributes.

	*/
	Body *models.MsgVpnRestDeliveryPointQueueBinding
	/*MsgVpnName
	  The name of the Message VPN.

	*/
	MsgVpnName string
	/*QueueBindingName
	  The name of a queue in the Message VPN.

	*/
	QueueBindingName string
	/*RestDeliveryPointName
	  The name of the REST Delivery Point.

	*/
	RestDeliveryPointName string
	/*Select
	  Include in the response only selected attributes of the object, or exclude from the response selected attributes of the object. See the documentation for the `select` parameter.

	*/
	Select []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update msg vpn rest delivery point queue binding params
func (o *UpdateMsgVpnRestDeliveryPointQueueBindingParams) WithTimeout(timeout time.Duration) *UpdateMsgVpnRestDeliveryPointQueueBindingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update msg vpn rest delivery point queue binding params
func (o *UpdateMsgVpnRestDeliveryPointQueueBindingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update msg vpn rest delivery point queue binding params
func (o *UpdateMsgVpnRestDeliveryPointQueueBindingParams) WithContext(ctx context.Context) *UpdateMsgVpnRestDeliveryPointQueueBindingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update msg vpn rest delivery point queue binding params
func (o *UpdateMsgVpnRestDeliveryPointQueueBindingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update msg vpn rest delivery point queue binding params
func (o *UpdateMsgVpnRestDeliveryPointQueueBindingParams) WithHTTPClient(client *http.Client) *UpdateMsgVpnRestDeliveryPointQueueBindingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update msg vpn rest delivery point queue binding params
func (o *UpdateMsgVpnRestDeliveryPointQueueBindingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update msg vpn rest delivery point queue binding params
func (o *UpdateMsgVpnRestDeliveryPointQueueBindingParams) WithBody(body *models.MsgVpnRestDeliveryPointQueueBinding) *UpdateMsgVpnRestDeliveryPointQueueBindingParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update msg vpn rest delivery point queue binding params
func (o *UpdateMsgVpnRestDeliveryPointQueueBindingParams) SetBody(body *models.MsgVpnRestDeliveryPointQueueBinding) {
	o.Body = body
}

// WithMsgVpnName adds the msgVpnName to the update msg vpn rest delivery point queue binding params
func (o *UpdateMsgVpnRestDeliveryPointQueueBindingParams) WithMsgVpnName(msgVpnName string) *UpdateMsgVpnRestDeliveryPointQueueBindingParams {
	o.SetMsgVpnName(msgVpnName)
	return o
}

// SetMsgVpnName adds the msgVpnName to the update msg vpn rest delivery point queue binding params
func (o *UpdateMsgVpnRestDeliveryPointQueueBindingParams) SetMsgVpnName(msgVpnName string) {
	o.MsgVpnName = msgVpnName
}

// WithQueueBindingName adds the queueBindingName to the update msg vpn rest delivery point queue binding params
func (o *UpdateMsgVpnRestDeliveryPointQueueBindingParams) WithQueueBindingName(queueBindingName string) *UpdateMsgVpnRestDeliveryPointQueueBindingParams {
	o.SetQueueBindingName(queueBindingName)
	return o
}

// SetQueueBindingName adds the queueBindingName to the update msg vpn rest delivery point queue binding params
func (o *UpdateMsgVpnRestDeliveryPointQueueBindingParams) SetQueueBindingName(queueBindingName string) {
	o.QueueBindingName = queueBindingName
}

// WithRestDeliveryPointName adds the restDeliveryPointName to the update msg vpn rest delivery point queue binding params
func (o *UpdateMsgVpnRestDeliveryPointQueueBindingParams) WithRestDeliveryPointName(restDeliveryPointName string) *UpdateMsgVpnRestDeliveryPointQueueBindingParams {
	o.SetRestDeliveryPointName(restDeliveryPointName)
	return o
}

// SetRestDeliveryPointName adds the restDeliveryPointName to the update msg vpn rest delivery point queue binding params
func (o *UpdateMsgVpnRestDeliveryPointQueueBindingParams) SetRestDeliveryPointName(restDeliveryPointName string) {
	o.RestDeliveryPointName = restDeliveryPointName
}

// WithSelect adds the selectVar to the update msg vpn rest delivery point queue binding params
func (o *UpdateMsgVpnRestDeliveryPointQueueBindingParams) WithSelect(selectVar []string) *UpdateMsgVpnRestDeliveryPointQueueBindingParams {
	o.SetSelect(selectVar)
	return o
}

// SetSelect adds the select to the update msg vpn rest delivery point queue binding params
func (o *UpdateMsgVpnRestDeliveryPointQueueBindingParams) SetSelect(selectVar []string) {
	o.Select = selectVar
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateMsgVpnRestDeliveryPointQueueBindingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param msgVpnName
	if err := r.SetPathParam("msgVpnName", o.MsgVpnName); err != nil {
		return err
	}

	// path param queueBindingName
	if err := r.SetPathParam("queueBindingName", o.QueueBindingName); err != nil {
		return err
	}

	// path param restDeliveryPointName
	if err := r.SetPathParam("restDeliveryPointName", o.RestDeliveryPointName); err != nil {
		return err
	}

	valuesSelect := o.Select

	joinedSelect := swag.JoinByFormat(valuesSelect, "csv")
	// query array param select
	if err := r.SetQueryParam("select", joinedSelect...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
