// Code generated by go-swagger; DO NOT EDIT.

package dmr_cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// NewCreateDmrClusterLinkRemoteAddressParams creates a new CreateDmrClusterLinkRemoteAddressParams object
// with the default values initialized.
func NewCreateDmrClusterLinkRemoteAddressParams() *CreateDmrClusterLinkRemoteAddressParams {
	var ()
	return &CreateDmrClusterLinkRemoteAddressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDmrClusterLinkRemoteAddressParamsWithTimeout creates a new CreateDmrClusterLinkRemoteAddressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateDmrClusterLinkRemoteAddressParamsWithTimeout(timeout time.Duration) *CreateDmrClusterLinkRemoteAddressParams {
	var ()
	return &CreateDmrClusterLinkRemoteAddressParams{

		timeout: timeout,
	}
}

// NewCreateDmrClusterLinkRemoteAddressParamsWithContext creates a new CreateDmrClusterLinkRemoteAddressParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateDmrClusterLinkRemoteAddressParamsWithContext(ctx context.Context) *CreateDmrClusterLinkRemoteAddressParams {
	var ()
	return &CreateDmrClusterLinkRemoteAddressParams{

		Context: ctx,
	}
}

// NewCreateDmrClusterLinkRemoteAddressParamsWithHTTPClient creates a new CreateDmrClusterLinkRemoteAddressParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateDmrClusterLinkRemoteAddressParamsWithHTTPClient(client *http.Client) *CreateDmrClusterLinkRemoteAddressParams {
	var ()
	return &CreateDmrClusterLinkRemoteAddressParams{
		HTTPClient: client,
	}
}

/*CreateDmrClusterLinkRemoteAddressParams contains all the parameters to send to the API endpoint
for the create dmr cluster link remote address operation typically these are written to a http.Request
*/
type CreateDmrClusterLinkRemoteAddressParams struct {

	/*Body
	  The Remote Address object's attributes.

	*/
	Body *models.DmrClusterLinkRemoteAddress
	/*DmrClusterName
	  The name of the Cluster.

	*/
	DmrClusterName string
	/*RemoteNodeName
	  The name of the node at the remote end of the Link.

	*/
	RemoteNodeName string
	/*Select
	  Include in the response only selected attributes of the object, or exclude from the response selected attributes of the object. See the documentation for the `select` parameter.

	*/
	Select []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create dmr cluster link remote address params
func (o *CreateDmrClusterLinkRemoteAddressParams) WithTimeout(timeout time.Duration) *CreateDmrClusterLinkRemoteAddressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create dmr cluster link remote address params
func (o *CreateDmrClusterLinkRemoteAddressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create dmr cluster link remote address params
func (o *CreateDmrClusterLinkRemoteAddressParams) WithContext(ctx context.Context) *CreateDmrClusterLinkRemoteAddressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create dmr cluster link remote address params
func (o *CreateDmrClusterLinkRemoteAddressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create dmr cluster link remote address params
func (o *CreateDmrClusterLinkRemoteAddressParams) WithHTTPClient(client *http.Client) *CreateDmrClusterLinkRemoteAddressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create dmr cluster link remote address params
func (o *CreateDmrClusterLinkRemoteAddressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create dmr cluster link remote address params
func (o *CreateDmrClusterLinkRemoteAddressParams) WithBody(body *models.DmrClusterLinkRemoteAddress) *CreateDmrClusterLinkRemoteAddressParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create dmr cluster link remote address params
func (o *CreateDmrClusterLinkRemoteAddressParams) SetBody(body *models.DmrClusterLinkRemoteAddress) {
	o.Body = body
}

// WithDmrClusterName adds the dmrClusterName to the create dmr cluster link remote address params
func (o *CreateDmrClusterLinkRemoteAddressParams) WithDmrClusterName(dmrClusterName string) *CreateDmrClusterLinkRemoteAddressParams {
	o.SetDmrClusterName(dmrClusterName)
	return o
}

// SetDmrClusterName adds the dmrClusterName to the create dmr cluster link remote address params
func (o *CreateDmrClusterLinkRemoteAddressParams) SetDmrClusterName(dmrClusterName string) {
	o.DmrClusterName = dmrClusterName
}

// WithRemoteNodeName adds the remoteNodeName to the create dmr cluster link remote address params
func (o *CreateDmrClusterLinkRemoteAddressParams) WithRemoteNodeName(remoteNodeName string) *CreateDmrClusterLinkRemoteAddressParams {
	o.SetRemoteNodeName(remoteNodeName)
	return o
}

// SetRemoteNodeName adds the remoteNodeName to the create dmr cluster link remote address params
func (o *CreateDmrClusterLinkRemoteAddressParams) SetRemoteNodeName(remoteNodeName string) {
	o.RemoteNodeName = remoteNodeName
}

// WithSelect adds the selectVar to the create dmr cluster link remote address params
func (o *CreateDmrClusterLinkRemoteAddressParams) WithSelect(selectVar []string) *CreateDmrClusterLinkRemoteAddressParams {
	o.SetSelect(selectVar)
	return o
}

// SetSelect adds the select to the create dmr cluster link remote address params
func (o *CreateDmrClusterLinkRemoteAddressParams) SetSelect(selectVar []string) {
	o.Select = selectVar
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDmrClusterLinkRemoteAddressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param dmrClusterName
	if err := r.SetPathParam("dmrClusterName", o.DmrClusterName); err != nil {
		return err
	}

	// path param remoteNodeName
	if err := r.SetPathParam("remoteNodeName", o.RemoteNodeName); err != nil {
		return err
	}

	valuesSelect := o.Select

	joinedSelect := swag.JoinByFormat(valuesSelect, "csv")
	// query array param select
	if err := r.SetQueryParam("select", joinedSelect...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
