// Code generated by go-swagger; DO NOT EDIT.

package dmr_cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDmrClusterLinkParams creates a new DeleteDmrClusterLinkParams object
// with the default values initialized.
func NewDeleteDmrClusterLinkParams() *DeleteDmrClusterLinkParams {
	var ()
	return &DeleteDmrClusterLinkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDmrClusterLinkParamsWithTimeout creates a new DeleteDmrClusterLinkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDmrClusterLinkParamsWithTimeout(timeout time.Duration) *DeleteDmrClusterLinkParams {
	var ()
	return &DeleteDmrClusterLinkParams{

		timeout: timeout,
	}
}

// NewDeleteDmrClusterLinkParamsWithContext creates a new DeleteDmrClusterLinkParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDmrClusterLinkParamsWithContext(ctx context.Context) *DeleteDmrClusterLinkParams {
	var ()
	return &DeleteDmrClusterLinkParams{

		Context: ctx,
	}
}

// NewDeleteDmrClusterLinkParamsWithHTTPClient creates a new DeleteDmrClusterLinkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDmrClusterLinkParamsWithHTTPClient(client *http.Client) *DeleteDmrClusterLinkParams {
	var ()
	return &DeleteDmrClusterLinkParams{
		HTTPClient: client,
	}
}

/*DeleteDmrClusterLinkParams contains all the parameters to send to the API endpoint
for the delete dmr cluster link operation typically these are written to a http.Request
*/
type DeleteDmrClusterLinkParams struct {

	/*DmrClusterName
	  The name of the Cluster.

	*/
	DmrClusterName string
	/*RemoteNodeName
	  The name of the node at the remote end of the Link.

	*/
	RemoteNodeName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete dmr cluster link params
func (o *DeleteDmrClusterLinkParams) WithTimeout(timeout time.Duration) *DeleteDmrClusterLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete dmr cluster link params
func (o *DeleteDmrClusterLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete dmr cluster link params
func (o *DeleteDmrClusterLinkParams) WithContext(ctx context.Context) *DeleteDmrClusterLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete dmr cluster link params
func (o *DeleteDmrClusterLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete dmr cluster link params
func (o *DeleteDmrClusterLinkParams) WithHTTPClient(client *http.Client) *DeleteDmrClusterLinkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete dmr cluster link params
func (o *DeleteDmrClusterLinkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDmrClusterName adds the dmrClusterName to the delete dmr cluster link params
func (o *DeleteDmrClusterLinkParams) WithDmrClusterName(dmrClusterName string) *DeleteDmrClusterLinkParams {
	o.SetDmrClusterName(dmrClusterName)
	return o
}

// SetDmrClusterName adds the dmrClusterName to the delete dmr cluster link params
func (o *DeleteDmrClusterLinkParams) SetDmrClusterName(dmrClusterName string) {
	o.DmrClusterName = dmrClusterName
}

// WithRemoteNodeName adds the remoteNodeName to the delete dmr cluster link params
func (o *DeleteDmrClusterLinkParams) WithRemoteNodeName(remoteNodeName string) *DeleteDmrClusterLinkParams {
	o.SetRemoteNodeName(remoteNodeName)
	return o
}

// SetRemoteNodeName adds the remoteNodeName to the delete dmr cluster link params
func (o *DeleteDmrClusterLinkParams) SetRemoteNodeName(remoteNodeName string) {
	o.RemoteNodeName = remoteNodeName
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDmrClusterLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param dmrClusterName
	if err := r.SetPathParam("dmrClusterName", o.DmrClusterName); err != nil {
		return err
	}

	// path param remoteNodeName
	if err := r.SetPathParam("remoteNodeName", o.RemoteNodeName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
