// Code generated by go-swagger; DO NOT EDIT.

package dmr_cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// DeleteDmrClusterReader is a Reader for the DeleteDmrCluster structure.
type DeleteDmrClusterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDmrClusterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteDmrClusterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteDmrClusterDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteDmrClusterOK creates a DeleteDmrClusterOK with default headers values
func NewDeleteDmrClusterOK() *DeleteDmrClusterOK {
	return &DeleteDmrClusterOK{}
}

/*DeleteDmrClusterOK handles this case with default header values.

The request metadata.
*/
type DeleteDmrClusterOK struct {
	Payload *models.SempMetaOnlyResponse
}

func (o *DeleteDmrClusterOK) Error() string {
	return fmt.Sprintf("[DELETE /dmrClusters/{dmrClusterName}][%d] deleteDmrClusterOK  %+v", 200, o.Payload)
}

func (o *DeleteDmrClusterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDmrClusterDefault creates a DeleteDmrClusterDefault with default headers values
func NewDeleteDmrClusterDefault(code int) *DeleteDmrClusterDefault {
	return &DeleteDmrClusterDefault{
		_statusCode: code,
	}
}

/*DeleteDmrClusterDefault handles this case with default header values.

The error response.
*/
type DeleteDmrClusterDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the delete dmr cluster default response
func (o *DeleteDmrClusterDefault) Code() int {
	return o._statusCode
}

func (o *DeleteDmrClusterDefault) Error() string {
	return fmt.Sprintf("[DELETE /dmrClusters/{dmrClusterName}][%d] deleteDmrCluster default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteDmrClusterDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
