// Code generated by go-swagger; DO NOT EDIT.

package dmr_cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// DeleteDmrClusterLinkReader is a Reader for the DeleteDmrClusterLink structure.
type DeleteDmrClusterLinkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDmrClusterLinkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteDmrClusterLinkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteDmrClusterLinkDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteDmrClusterLinkOK creates a DeleteDmrClusterLinkOK with default headers values
func NewDeleteDmrClusterLinkOK() *DeleteDmrClusterLinkOK {
	return &DeleteDmrClusterLinkOK{}
}

/*DeleteDmrClusterLinkOK handles this case with default header values.

The request metadata.
*/
type DeleteDmrClusterLinkOK struct {
	Payload *models.SempMetaOnlyResponse
}

func (o *DeleteDmrClusterLinkOK) Error() string {
	return fmt.Sprintf("[DELETE /dmrClusters/{dmrClusterName}/links/{remoteNodeName}][%d] deleteDmrClusterLinkOK  %+v", 200, o.Payload)
}

func (o *DeleteDmrClusterLinkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDmrClusterLinkDefault creates a DeleteDmrClusterLinkDefault with default headers values
func NewDeleteDmrClusterLinkDefault(code int) *DeleteDmrClusterLinkDefault {
	return &DeleteDmrClusterLinkDefault{
		_statusCode: code,
	}
}

/*DeleteDmrClusterLinkDefault handles this case with default header values.

The error response.
*/
type DeleteDmrClusterLinkDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the delete dmr cluster link default response
func (o *DeleteDmrClusterLinkDefault) Code() int {
	return o._statusCode
}

func (o *DeleteDmrClusterLinkDefault) Error() string {
	return fmt.Sprintf("[DELETE /dmrClusters/{dmrClusterName}/links/{remoteNodeName}][%d] deleteDmrClusterLink default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteDmrClusterLinkDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
