// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AboutUserMsgVpnLinks about user msg vpn links
// swagger:model AboutUserMsgVpnLinks
type AboutUserMsgVpnLinks struct {

	// The URI of this User Message VPN object.
	URI string `json:"uri,omitempty"`
}

// Validate validates this about user msg vpn links
func (m *AboutUserMsgVpnLinks) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AboutUserMsgVpnLinks) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AboutUserMsgVpnLinks) UnmarshalBinary(b []byte) error {
	var res AboutUserMsgVpnLinks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
