// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MsgVpnRestDeliveryPoint msg vpn rest delivery point
// swagger:model MsgVpnRestDeliveryPoint
type MsgVpnRestDeliveryPoint struct {

	// The Client Profile of the REST Delivery Point. It must exist in the local Message VPN. Its TCP parameters are used for all REST Consumers in this RDP. Its queue properties are used by the RDP client. The Client Profile is used inside the auto-generated Client Username for this RDP. The default value is `"default"`.
	ClientProfileName string `json:"clientProfileName,omitempty"`

	// Enable or disable the REST Delivery Point. When disabled, no connections are initiated or messages delivered to any of the contained REST Consumers. The default value is `false`.
	Enabled bool `json:"enabled,omitempty"`

	// The name of the Message VPN.
	MsgVpnName string `json:"msgVpnName,omitempty"`

	// The name of the REST Delivery Point.
	RestDeliveryPointName string `json:"restDeliveryPointName,omitempty"`
}

// Validate validates this msg vpn rest delivery point
func (m *MsgVpnRestDeliveryPoint) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MsgVpnRestDeliveryPoint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MsgVpnRestDeliveryPoint) UnmarshalBinary(b []byte) error {
	var res MsgVpnRestDeliveryPoint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
