// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MsgVpnReplicatedTopicLinks msg vpn replicated topic links
// swagger:model MsgVpnReplicatedTopicLinks
type MsgVpnReplicatedTopicLinks struct {

	// The URI of this Replicated Topic object.
	URI string `json:"uri,omitempty"`
}

// Validate validates this msg vpn replicated topic links
func (m *MsgVpnReplicatedTopicLinks) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MsgVpnReplicatedTopicLinks) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MsgVpnReplicatedTopicLinks) UnmarshalBinary(b []byte) error {
	var res MsgVpnReplicatedTopicLinks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
