// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MsgVpnACLProfileLinks msg vpn Acl profile links
// swagger:model MsgVpnAclProfileLinks
type MsgVpnACLProfileLinks struct {

	// The URI of this MsgVpnAclProfile's clientConnectExceptions collection.
	ClientConnectExceptionsURI string `json:"clientConnectExceptionsUri,omitempty"`

	// The URI of this MsgVpnAclProfile's publishExceptions collection.
	PublishExceptionsURI string `json:"publishExceptionsUri,omitempty"`

	// The URI of this MsgVpnAclProfile's subscribeExceptions collection.
	SubscribeExceptionsURI string `json:"subscribeExceptionsUri,omitempty"`

	// The URI of this MsgVpnAclProfile object.
	URI string `json:"uri,omitempty"`
}

// Validate validates this msg vpn Acl profile links
func (m *MsgVpnACLProfileLinks) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MsgVpnACLProfileLinks) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MsgVpnACLProfileLinks) UnmarshalBinary(b []byte) error {
	var res MsgVpnACLProfileLinks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
