// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MsgVpnRestDeliveryPointRestConsumerLinks msg vpn rest delivery point rest consumer links
// swagger:model MsgVpnRestDeliveryPointRestConsumerLinks
type MsgVpnRestDeliveryPointRestConsumerLinks struct {

	// The URI of this REST Consumer's collection of Trusted Common Name objects. Available since 2.7.
	TLSTrustedCommonNamesURI string `json:"tlsTrustedCommonNamesUri,omitempty"`

	// The URI of this REST Consumer object.
	URI string `json:"uri,omitempty"`
}

// Validate validates this msg vpn rest delivery point rest consumer links
func (m *MsgVpnRestDeliveryPointRestConsumerLinks) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MsgVpnRestDeliveryPointRestConsumerLinks) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MsgVpnRestDeliveryPointRestConsumerLinks) UnmarshalBinary(b []byte) error {
	var res MsgVpnRestDeliveryPointRestConsumerLinks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
