// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MsgVpnDistributedCacheClusterLinks msg vpn distributed cache cluster links
// swagger:model MsgVpnDistributedCacheClusterLinks
type MsgVpnDistributedCacheClusterLinks struct {

	// The URI of this Cache Cluster's collection of Home Cache Cluster objects.
	GlobalCachingHomeClustersURI string `json:"globalCachingHomeClustersUri,omitempty"`

	// The URI of this Cache Cluster's collection of Cache Instance objects.
	InstancesURI string `json:"instancesUri,omitempty"`

	// The URI of this Cache Cluster's collection of Topic objects.
	TopicsURI string `json:"topicsUri,omitempty"`

	// The URI of this Cache Cluster object.
	URI string `json:"uri,omitempty"`
}

// Validate validates this msg vpn distributed cache cluster links
func (m *MsgVpnDistributedCacheClusterLinks) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MsgVpnDistributedCacheClusterLinks) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MsgVpnDistributedCacheClusterLinks) UnmarshalBinary(b []byte) error {
	var res MsgVpnDistributedCacheClusterLinks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
