// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MsgVpnQueueSubscription msg vpn queue subscription
// swagger:model MsgVpnQueueSubscription
type MsgVpnQueueSubscription struct {

	// The name of the Message VPN.
	MsgVpnName string `json:"msgVpnName,omitempty"`

	// The name of the Queue.
	QueueName string `json:"queueName,omitempty"`

	// The topic of the Subscription.
	SubscriptionTopic string `json:"subscriptionTopic,omitempty"`
}

// Validate validates this msg vpn queue subscription
func (m *MsgVpnQueueSubscription) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MsgVpnQueueSubscription) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MsgVpnQueueSubscription) UnmarshalBinary(b []byte) error {
	var res MsgVpnQueueSubscription
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
