// Code generated by go-swagger; DO NOT EDIT.

package username

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteUsernameMsgVpnAccessLevelExceptionParams creates a new DeleteUsernameMsgVpnAccessLevelExceptionParams object
// with the default values initialized.
func NewDeleteUsernameMsgVpnAccessLevelExceptionParams() *DeleteUsernameMsgVpnAccessLevelExceptionParams {
	var ()
	return &DeleteUsernameMsgVpnAccessLevelExceptionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteUsernameMsgVpnAccessLevelExceptionParamsWithTimeout creates a new DeleteUsernameMsgVpnAccessLevelExceptionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteUsernameMsgVpnAccessLevelExceptionParamsWithTimeout(timeout time.Duration) *DeleteUsernameMsgVpnAccessLevelExceptionParams {
	var ()
	return &DeleteUsernameMsgVpnAccessLevelExceptionParams{

		timeout: timeout,
	}
}

// NewDeleteUsernameMsgVpnAccessLevelExceptionParamsWithContext creates a new DeleteUsernameMsgVpnAccessLevelExceptionParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteUsernameMsgVpnAccessLevelExceptionParamsWithContext(ctx context.Context) *DeleteUsernameMsgVpnAccessLevelExceptionParams {
	var ()
	return &DeleteUsernameMsgVpnAccessLevelExceptionParams{

		Context: ctx,
	}
}

// NewDeleteUsernameMsgVpnAccessLevelExceptionParamsWithHTTPClient creates a new DeleteUsernameMsgVpnAccessLevelExceptionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteUsernameMsgVpnAccessLevelExceptionParamsWithHTTPClient(client *http.Client) *DeleteUsernameMsgVpnAccessLevelExceptionParams {
	var ()
	return &DeleteUsernameMsgVpnAccessLevelExceptionParams{
		HTTPClient: client,
	}
}

/*DeleteUsernameMsgVpnAccessLevelExceptionParams contains all the parameters to send to the API endpoint
for the delete username msg vpn access level exception operation typically these are written to a http.Request
*/
type DeleteUsernameMsgVpnAccessLevelExceptionParams struct {

	/*MsgVpnName
	  The name of the Message VPN for which an access level exception may be configured.

	*/
	MsgVpnName string
	/*UserName
	  Username.

	*/
	UserName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete username msg vpn access level exception params
func (o *DeleteUsernameMsgVpnAccessLevelExceptionParams) WithTimeout(timeout time.Duration) *DeleteUsernameMsgVpnAccessLevelExceptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete username msg vpn access level exception params
func (o *DeleteUsernameMsgVpnAccessLevelExceptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete username msg vpn access level exception params
func (o *DeleteUsernameMsgVpnAccessLevelExceptionParams) WithContext(ctx context.Context) *DeleteUsernameMsgVpnAccessLevelExceptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete username msg vpn access level exception params
func (o *DeleteUsernameMsgVpnAccessLevelExceptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete username msg vpn access level exception params
func (o *DeleteUsernameMsgVpnAccessLevelExceptionParams) WithHTTPClient(client *http.Client) *DeleteUsernameMsgVpnAccessLevelExceptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete username msg vpn access level exception params
func (o *DeleteUsernameMsgVpnAccessLevelExceptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMsgVpnName adds the msgVpnName to the delete username msg vpn access level exception params
func (o *DeleteUsernameMsgVpnAccessLevelExceptionParams) WithMsgVpnName(msgVpnName string) *DeleteUsernameMsgVpnAccessLevelExceptionParams {
	o.SetMsgVpnName(msgVpnName)
	return o
}

// SetMsgVpnName adds the msgVpnName to the delete username msg vpn access level exception params
func (o *DeleteUsernameMsgVpnAccessLevelExceptionParams) SetMsgVpnName(msgVpnName string) {
	o.MsgVpnName = msgVpnName
}

// WithUserName adds the userName to the delete username msg vpn access level exception params
func (o *DeleteUsernameMsgVpnAccessLevelExceptionParams) WithUserName(userName string) *DeleteUsernameMsgVpnAccessLevelExceptionParams {
	o.SetUserName(userName)
	return o
}

// SetUserName adds the userName to the delete username msg vpn access level exception params
func (o *DeleteUsernameMsgVpnAccessLevelExceptionParams) SetUserName(userName string) {
	o.UserName = userName
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUsernameMsgVpnAccessLevelExceptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param msgVpnName
	if err := r.SetPathParam("msgVpnName", o.MsgVpnName); err != nil {
		return err
	}

	// path param userName
	if err := r.SetPathParam("userName", o.UserName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
