// Code generated by go-swagger; DO NOT EDIT.

package username

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUsernameMsgVpnAccessLevelExceptionsParams creates a new GetUsernameMsgVpnAccessLevelExceptionsParams object
// with the default values initialized.
func NewGetUsernameMsgVpnAccessLevelExceptionsParams() *GetUsernameMsgVpnAccessLevelExceptionsParams {
	var (
		countDefault = int64(10)
	)
	return &GetUsernameMsgVpnAccessLevelExceptionsParams{
		Count: &countDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsernameMsgVpnAccessLevelExceptionsParamsWithTimeout creates a new GetUsernameMsgVpnAccessLevelExceptionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUsernameMsgVpnAccessLevelExceptionsParamsWithTimeout(timeout time.Duration) *GetUsernameMsgVpnAccessLevelExceptionsParams {
	var (
		countDefault = int64(10)
	)
	return &GetUsernameMsgVpnAccessLevelExceptionsParams{
		Count: &countDefault,

		timeout: timeout,
	}
}

// NewGetUsernameMsgVpnAccessLevelExceptionsParamsWithContext creates a new GetUsernameMsgVpnAccessLevelExceptionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUsernameMsgVpnAccessLevelExceptionsParamsWithContext(ctx context.Context) *GetUsernameMsgVpnAccessLevelExceptionsParams {
	var (
		countDefault = int64(10)
	)
	return &GetUsernameMsgVpnAccessLevelExceptionsParams{
		Count: &countDefault,

		Context: ctx,
	}
}

// NewGetUsernameMsgVpnAccessLevelExceptionsParamsWithHTTPClient creates a new GetUsernameMsgVpnAccessLevelExceptionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUsernameMsgVpnAccessLevelExceptionsParamsWithHTTPClient(client *http.Client) *GetUsernameMsgVpnAccessLevelExceptionsParams {
	var (
		countDefault = int64(10)
	)
	return &GetUsernameMsgVpnAccessLevelExceptionsParams{
		Count:      &countDefault,
		HTTPClient: client,
	}
}

/*GetUsernameMsgVpnAccessLevelExceptionsParams contains all the parameters to send to the API endpoint
for the get username msg vpn access level exceptions operation typically these are written to a http.Request
*/
type GetUsernameMsgVpnAccessLevelExceptionsParams struct {

	/*Count
	  Limit the count of objects in the response. See the documentation for the `count` parameter.

	*/
	Count *int64
	/*Cursor
	  The cursor, or position, for the next page of objects. See the documentation for the `cursor` parameter.

	*/
	Cursor *string
	/*Select
	  Include in the response only selected attributes of the object, or exclude from the response selected attributes of the object. See the documentation for the `select` parameter.

	*/
	Select []string
	/*UserName
	  Username.

	*/
	UserName string
	/*Where
	  Include in the response only objects where certain conditions are true. See the the documentation for the `where` parameter.

	*/
	Where []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get username msg vpn access level exceptions params
func (o *GetUsernameMsgVpnAccessLevelExceptionsParams) WithTimeout(timeout time.Duration) *GetUsernameMsgVpnAccessLevelExceptionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get username msg vpn access level exceptions params
func (o *GetUsernameMsgVpnAccessLevelExceptionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get username msg vpn access level exceptions params
func (o *GetUsernameMsgVpnAccessLevelExceptionsParams) WithContext(ctx context.Context) *GetUsernameMsgVpnAccessLevelExceptionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get username msg vpn access level exceptions params
func (o *GetUsernameMsgVpnAccessLevelExceptionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get username msg vpn access level exceptions params
func (o *GetUsernameMsgVpnAccessLevelExceptionsParams) WithHTTPClient(client *http.Client) *GetUsernameMsgVpnAccessLevelExceptionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get username msg vpn access level exceptions params
func (o *GetUsernameMsgVpnAccessLevelExceptionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCount adds the count to the get username msg vpn access level exceptions params
func (o *GetUsernameMsgVpnAccessLevelExceptionsParams) WithCount(count *int64) *GetUsernameMsgVpnAccessLevelExceptionsParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the get username msg vpn access level exceptions params
func (o *GetUsernameMsgVpnAccessLevelExceptionsParams) SetCount(count *int64) {
	o.Count = count
}

// WithCursor adds the cursor to the get username msg vpn access level exceptions params
func (o *GetUsernameMsgVpnAccessLevelExceptionsParams) WithCursor(cursor *string) *GetUsernameMsgVpnAccessLevelExceptionsParams {
	o.SetCursor(cursor)
	return o
}

// SetCursor adds the cursor to the get username msg vpn access level exceptions params
func (o *GetUsernameMsgVpnAccessLevelExceptionsParams) SetCursor(cursor *string) {
	o.Cursor = cursor
}

// WithSelect adds the selectVar to the get username msg vpn access level exceptions params
func (o *GetUsernameMsgVpnAccessLevelExceptionsParams) WithSelect(selectVar []string) *GetUsernameMsgVpnAccessLevelExceptionsParams {
	o.SetSelect(selectVar)
	return o
}

// SetSelect adds the select to the get username msg vpn access level exceptions params
func (o *GetUsernameMsgVpnAccessLevelExceptionsParams) SetSelect(selectVar []string) {
	o.Select = selectVar
}

// WithUserName adds the userName to the get username msg vpn access level exceptions params
func (o *GetUsernameMsgVpnAccessLevelExceptionsParams) WithUserName(userName string) *GetUsernameMsgVpnAccessLevelExceptionsParams {
	o.SetUserName(userName)
	return o
}

// SetUserName adds the userName to the get username msg vpn access level exceptions params
func (o *GetUsernameMsgVpnAccessLevelExceptionsParams) SetUserName(userName string) {
	o.UserName = userName
}

// WithWhere adds the where to the get username msg vpn access level exceptions params
func (o *GetUsernameMsgVpnAccessLevelExceptionsParams) WithWhere(where []string) *GetUsernameMsgVpnAccessLevelExceptionsParams {
	o.SetWhere(where)
	return o
}

// SetWhere adds the where to the get username msg vpn access level exceptions params
func (o *GetUsernameMsgVpnAccessLevelExceptionsParams) SetWhere(where []string) {
	o.Where = where
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsernameMsgVpnAccessLevelExceptionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Count != nil {

		// query param count
		var qrCount int64
		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatInt64(qrCount)
		if qCount != "" {
			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}

	}

	if o.Cursor != nil {

		// query param cursor
		var qrCursor string
		if o.Cursor != nil {
			qrCursor = *o.Cursor
		}
		qCursor := qrCursor
		if qCursor != "" {
			if err := r.SetQueryParam("cursor", qCursor); err != nil {
				return err
			}
		}

	}

	valuesSelect := o.Select

	joinedSelect := swag.JoinByFormat(valuesSelect, "csv")
	// query array param select
	if err := r.SetQueryParam("select", joinedSelect...); err != nil {
		return err
	}

	// path param userName
	if err := r.SetPathParam("userName", o.UserName); err != nil {
		return err
	}

	valuesWhere := o.Where

	joinedWhere := swag.JoinByFormat(valuesWhere, "csv")
	// query array param where
	if err := r.SetQueryParam("where", joinedWhere...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
