// Code generated by go-swagger; DO NOT EDIT.

package username

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// GetUsernameMsgVpnAccessLevelExceptionReader is a Reader for the GetUsernameMsgVpnAccessLevelException structure.
type GetUsernameMsgVpnAccessLevelExceptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsernameMsgVpnAccessLevelExceptionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetUsernameMsgVpnAccessLevelExceptionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetUsernameMsgVpnAccessLevelExceptionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetUsernameMsgVpnAccessLevelExceptionOK creates a GetUsernameMsgVpnAccessLevelExceptionOK with default headers values
func NewGetUsernameMsgVpnAccessLevelExceptionOK() *GetUsernameMsgVpnAccessLevelExceptionOK {
	return &GetUsernameMsgVpnAccessLevelExceptionOK{}
}

/*GetUsernameMsgVpnAccessLevelExceptionOK handles this case with default header values.

The Message VPN Access Level Exception object's attributes, and the request metadata.
*/
type GetUsernameMsgVpnAccessLevelExceptionOK struct {
	Payload *models.UsernameMsgVpnAccessLevelExceptionResponse
}

func (o *GetUsernameMsgVpnAccessLevelExceptionOK) Error() string {
	return fmt.Sprintf("[GET /usernames/{userName}/msgVpnAccessLevelExceptions/{msgVpnName}][%d] getUsernameMsgVpnAccessLevelExceptionOK  %+v", 200, o.Payload)
}

func (o *GetUsernameMsgVpnAccessLevelExceptionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UsernameMsgVpnAccessLevelExceptionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsernameMsgVpnAccessLevelExceptionDefault creates a GetUsernameMsgVpnAccessLevelExceptionDefault with default headers values
func NewGetUsernameMsgVpnAccessLevelExceptionDefault(code int) *GetUsernameMsgVpnAccessLevelExceptionDefault {
	return &GetUsernameMsgVpnAccessLevelExceptionDefault{
		_statusCode: code,
	}
}

/*GetUsernameMsgVpnAccessLevelExceptionDefault handles this case with default header values.

The error response.
*/
type GetUsernameMsgVpnAccessLevelExceptionDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the get username msg vpn access level exception default response
func (o *GetUsernameMsgVpnAccessLevelExceptionDefault) Code() int {
	return o._statusCode
}

func (o *GetUsernameMsgVpnAccessLevelExceptionDefault) Error() string {
	return fmt.Sprintf("[GET /usernames/{userName}/msgVpnAccessLevelExceptions/{msgVpnName}][%d] getUsernameMsgVpnAccessLevelException default  %+v", o._statusCode, o.Payload)
}

func (o *GetUsernameMsgVpnAccessLevelExceptionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
