// Code generated by go-swagger; DO NOT EDIT.

package username

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// NewReplaceUsernameMsgVpnAccessLevelExceptionParams creates a new ReplaceUsernameMsgVpnAccessLevelExceptionParams object
// with the default values initialized.
func NewReplaceUsernameMsgVpnAccessLevelExceptionParams() *ReplaceUsernameMsgVpnAccessLevelExceptionParams {
	var ()
	return &ReplaceUsernameMsgVpnAccessLevelExceptionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReplaceUsernameMsgVpnAccessLevelExceptionParamsWithTimeout creates a new ReplaceUsernameMsgVpnAccessLevelExceptionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReplaceUsernameMsgVpnAccessLevelExceptionParamsWithTimeout(timeout time.Duration) *ReplaceUsernameMsgVpnAccessLevelExceptionParams {
	var ()
	return &ReplaceUsernameMsgVpnAccessLevelExceptionParams{

		timeout: timeout,
	}
}

// NewReplaceUsernameMsgVpnAccessLevelExceptionParamsWithContext creates a new ReplaceUsernameMsgVpnAccessLevelExceptionParams object
// with the default values initialized, and the ability to set a context for a request
func NewReplaceUsernameMsgVpnAccessLevelExceptionParamsWithContext(ctx context.Context) *ReplaceUsernameMsgVpnAccessLevelExceptionParams {
	var ()
	return &ReplaceUsernameMsgVpnAccessLevelExceptionParams{

		Context: ctx,
	}
}

// NewReplaceUsernameMsgVpnAccessLevelExceptionParamsWithHTTPClient creates a new ReplaceUsernameMsgVpnAccessLevelExceptionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReplaceUsernameMsgVpnAccessLevelExceptionParamsWithHTTPClient(client *http.Client) *ReplaceUsernameMsgVpnAccessLevelExceptionParams {
	var ()
	return &ReplaceUsernameMsgVpnAccessLevelExceptionParams{
		HTTPClient: client,
	}
}

/*ReplaceUsernameMsgVpnAccessLevelExceptionParams contains all the parameters to send to the API endpoint
for the replace username msg vpn access level exception operation typically these are written to a http.Request
*/
type ReplaceUsernameMsgVpnAccessLevelExceptionParams struct {

	/*Body
	  The Message VPN Access Level Exception object's attributes.

	*/
	Body *models.UsernameMsgVpnAccessLevelException
	/*MsgVpnName
	  The name of the Message VPN for which an access level exception may be configured.

	*/
	MsgVpnName string
	/*Select
	  Include in the response only selected attributes of the object, or exclude from the response selected attributes of the object. See the documentation for the `select` parameter.

	*/
	Select []string
	/*UserName
	  Username.

	*/
	UserName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the replace username msg vpn access level exception params
func (o *ReplaceUsernameMsgVpnAccessLevelExceptionParams) WithTimeout(timeout time.Duration) *ReplaceUsernameMsgVpnAccessLevelExceptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the replace username msg vpn access level exception params
func (o *ReplaceUsernameMsgVpnAccessLevelExceptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the replace username msg vpn access level exception params
func (o *ReplaceUsernameMsgVpnAccessLevelExceptionParams) WithContext(ctx context.Context) *ReplaceUsernameMsgVpnAccessLevelExceptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the replace username msg vpn access level exception params
func (o *ReplaceUsernameMsgVpnAccessLevelExceptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the replace username msg vpn access level exception params
func (o *ReplaceUsernameMsgVpnAccessLevelExceptionParams) WithHTTPClient(client *http.Client) *ReplaceUsernameMsgVpnAccessLevelExceptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the replace username msg vpn access level exception params
func (o *ReplaceUsernameMsgVpnAccessLevelExceptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the replace username msg vpn access level exception params
func (o *ReplaceUsernameMsgVpnAccessLevelExceptionParams) WithBody(body *models.UsernameMsgVpnAccessLevelException) *ReplaceUsernameMsgVpnAccessLevelExceptionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the replace username msg vpn access level exception params
func (o *ReplaceUsernameMsgVpnAccessLevelExceptionParams) SetBody(body *models.UsernameMsgVpnAccessLevelException) {
	o.Body = body
}

// WithMsgVpnName adds the msgVpnName to the replace username msg vpn access level exception params
func (o *ReplaceUsernameMsgVpnAccessLevelExceptionParams) WithMsgVpnName(msgVpnName string) *ReplaceUsernameMsgVpnAccessLevelExceptionParams {
	o.SetMsgVpnName(msgVpnName)
	return o
}

// SetMsgVpnName adds the msgVpnName to the replace username msg vpn access level exception params
func (o *ReplaceUsernameMsgVpnAccessLevelExceptionParams) SetMsgVpnName(msgVpnName string) {
	o.MsgVpnName = msgVpnName
}

// WithSelect adds the selectVar to the replace username msg vpn access level exception params
func (o *ReplaceUsernameMsgVpnAccessLevelExceptionParams) WithSelect(selectVar []string) *ReplaceUsernameMsgVpnAccessLevelExceptionParams {
	o.SetSelect(selectVar)
	return o
}

// SetSelect adds the select to the replace username msg vpn access level exception params
func (o *ReplaceUsernameMsgVpnAccessLevelExceptionParams) SetSelect(selectVar []string) {
	o.Select = selectVar
}

// WithUserName adds the userName to the replace username msg vpn access level exception params
func (o *ReplaceUsernameMsgVpnAccessLevelExceptionParams) WithUserName(userName string) *ReplaceUsernameMsgVpnAccessLevelExceptionParams {
	o.SetUserName(userName)
	return o
}

// SetUserName adds the userName to the replace username msg vpn access level exception params
func (o *ReplaceUsernameMsgVpnAccessLevelExceptionParams) SetUserName(userName string) {
	o.UserName = userName
}

// WriteToRequest writes these params to a swagger request
func (o *ReplaceUsernameMsgVpnAccessLevelExceptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param msgVpnName
	if err := r.SetPathParam("msgVpnName", o.MsgVpnName); err != nil {
		return err
	}

	valuesSelect := o.Select

	joinedSelect := swag.JoinByFormat(valuesSelect, "csv")
	// query array param select
	if err := r.SetQueryParam("select", joinedSelect...); err != nil {
		return err
	}

	// path param userName
	if err := r.SetPathParam("userName", o.UserName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
