// Code generated by go-swagger; DO NOT EDIT.

package username

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ExalDraen/semp-client/models"
)

// UpdateUsernameReader is a Reader for the UpdateUsername structure.
type UpdateUsernameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateUsernameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateUsernameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewUpdateUsernameDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateUsernameOK creates a UpdateUsernameOK with default headers values
func NewUpdateUsernameOK() *UpdateUsernameOK {
	return &UpdateUsernameOK{}
}

/*UpdateUsernameOK handles this case with default header values.

The Username object's attributes after being updated, and the request metadata.
*/
type UpdateUsernameOK struct {
	Payload *models.UsernameResponse
}

func (o *UpdateUsernameOK) Error() string {
	return fmt.Sprintf("[PATCH /usernames/{userName}][%d] updateUsernameOK  %+v", 200, o.Payload)
}

func (o *UpdateUsernameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UsernameResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateUsernameDefault creates a UpdateUsernameDefault with default headers values
func NewUpdateUsernameDefault(code int) *UpdateUsernameDefault {
	return &UpdateUsernameDefault{
		_statusCode: code,
	}
}

/*UpdateUsernameDefault handles this case with default header values.

The error response.
*/
type UpdateUsernameDefault struct {
	_statusCode int

	Payload *models.SempMetaOnlyResponse
}

// Code gets the status code for the update username default response
func (o *UpdateUsernameDefault) Code() int {
	return o._statusCode
}

func (o *UpdateUsernameDefault) Error() string {
	return fmt.Sprintf("[PATCH /usernames/{userName}][%d] updateUsername default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateUsernameDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SempMetaOnlyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
